#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpic.Cprs2010.Cfg
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PatentQuery_ZJPT")]
	public partial class CfgDataManagerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCountryConfig(CountryConfig instance);
    partial void UpdateCountryConfig(CountryConfig instance);
    partial void DeleteCountryConfig(CountryConfig instance);
    partial void InsertTb_UsetPatentInfo(Tb_UsetPatentInfo instance);
    partial void UpdateTb_UsetPatentInfo(Tb_UsetPatentInfo instance);
    partial void DeleteTb_UsetPatentInfo(Tb_UsetPatentInfo instance);
    #endregion
		
		public CfgDataManagerDataContext() : 
				base(global::Cpic.Cprs2010.Cfg.Properties.Settings.Default.PatentQuery_ZJPTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CfgDataManagerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgDataManagerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgDataManagerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgDataManagerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CountryConfig> CountryConfig
		{
			get
			{
				return this.GetTable<CountryConfig>();
			}
		}
		
		public System.Data.Linq.Table<Tb_UsetPatentInfo> Tb_UsetPatentInfo
		{
			get
			{
				return this.GetTable<Tb_UsetPatentInfo>();
			}
		}
		
		public System.Data.Linq.Table<ZPT_SJWH_DLJGPZB> ZPT_SJWH_DLJGPZB
		{
			get
			{
				return this.GetTable<ZPT_SJWH_DLJGPZB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CountryConfig")]
	public partial class CountryConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _DaiMa;
		
		private string _MingCheng;
		
		private System.Nullable<byte> _leixing;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDaiMaChanging(string value);
    partial void OnDaiMaChanged();
    partial void OnMingChengChanging(string value);
    partial void OnMingChengChanged();
    partial void OnleixingChanging(System.Nullable<byte> value);
    partial void OnleixingChanged();
    #endregion
		
		public CountryConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaiMa", DbType="Char(4)")]
		public string DaiMa
		{
			get
			{
				return this._DaiMa;
			}
			set
			{
				if ((this._DaiMa != value))
				{
					this.OnDaiMaChanging(value);
					this.SendPropertyChanging();
					this._DaiMa = value;
					this.SendPropertyChanged("DaiMa");
					this.OnDaiMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MingCheng", DbType="VarChar(100)")]
		public string MingCheng
		{
			get
			{
				return this._MingCheng;
			}
			set
			{
				if ((this._MingCheng != value))
				{
					this.OnMingChengChanging(value);
					this.SendPropertyChanging();
					this._MingCheng = value;
					this.SendPropertyChanged("MingCheng");
					this.OnMingChengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leixing", DbType="TinyInt")]
		public System.Nullable<byte> leixing
		{
			get
			{
				return this._leixing;
			}
			set
			{
				if ((this._leixing != value))
				{
					this.OnleixingChanging(value);
					this.SendPropertyChanging();
					this._leixing = value;
					this.SendPropertyChanged("leixing");
					this.OnleixingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_UsetPatentInfo")]
	public partial class Tb_UsetPatentInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _UId;
		
		private string _ApNo;
		
		private string _Info;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUIdChanging(System.Nullable<int> value);
    partial void OnUIdChanged();
    partial void OnApNoChanging(string value);
    partial void OnApNoChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    #endregion
		
		public Tb_UsetPatentInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UId", DbType="Int")]
		public System.Nullable<int> UId
		{
			get
			{
				return this._UId;
			}
			set
			{
				if ((this._UId != value))
				{
					this.OnUIdChanging(value);
					this.SendPropertyChanging();
					this._UId = value;
					this.SendPropertyChanged("UId");
					this.OnUIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApNo", DbType="VarChar(12)")]
		public string ApNo
		{
			get
			{
				return this._ApNo;
			}
			set
			{
				if ((this._ApNo != value))
				{
					this.OnApNoChanging(value);
					this.SendPropertyChanging();
					this._ApNo = value;
					this.SendPropertyChanged("ApNo");
					this.OnApNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="VarChar(150)")]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZPT_SJWH_DLJGPZB")]
	public partial class ZPT_SJWH_DLJGPZB
	{
		
		private string _DAILIJGID;
		
		private string _DAILIJGDM;
		
		private string _DAILIJGDZ;
		
		private string _DAILIJGYB;
		
		private string _DAILIJGLXDH;
		
		private string _DAILIJGYHZH;
		
		private string _DAILIJGMC;
		
		private string _DAILIJGFZRXM;
		
		private string _DAILIJGBZH;
		
		private string _DAILIJGBZS;
		
		private string _SHANGJIZGDW;
		
		private string _PIBIANDW;
		
		private string _GONGSDJBJ;
		
		private string _ZHUANLIDJRQ;
		
		private string _DENGJIRQ;
		
		private string _JINGJIXZ;
		
		private string _DAILIJGZT;
		
		private string _SUOZAIDQ;
		
		private string _JINGYINGFW;
		
		private string _SHEWAIQBJ;
		
		private string _DAILIJGJC;
		
		private string _KEZIQXJBJ;
		
		private string _BIANGENGBJ;
		
		private string _REGNAME;
		
		private string _REGTIME;
		
		private string _MODNAME;
		
		private string _MODTIME;
		
		private string _YOUXIAOBJ;
		
		private string _NIANJIANZT;
		
		private string _DAILIJGYDDH;
		
		private string _CHENGJIECXGDQ;
		
		public ZPT_SJWH_DLJGPZB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGID", DbType="NVarChar(MAX)")]
		public string DAILIJGID
		{
			get
			{
				return this._DAILIJGID;
			}
			set
			{
				if ((this._DAILIJGID != value))
				{
					this._DAILIJGID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGDM", DbType="NVarChar(MAX)")]
		public string DAILIJGDM
		{
			get
			{
				return this._DAILIJGDM;
			}
			set
			{
				if ((this._DAILIJGDM != value))
				{
					this._DAILIJGDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGDZ", DbType="NVarChar(MAX)")]
		public string DAILIJGDZ
		{
			get
			{
				return this._DAILIJGDZ;
			}
			set
			{
				if ((this._DAILIJGDZ != value))
				{
					this._DAILIJGDZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGYB", DbType="NVarChar(MAX)")]
		public string DAILIJGYB
		{
			get
			{
				return this._DAILIJGYB;
			}
			set
			{
				if ((this._DAILIJGYB != value))
				{
					this._DAILIJGYB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGLXDH", DbType="NVarChar(MAX)")]
		public string DAILIJGLXDH
		{
			get
			{
				return this._DAILIJGLXDH;
			}
			set
			{
				if ((this._DAILIJGLXDH != value))
				{
					this._DAILIJGLXDH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGYHZH", DbType="NVarChar(MAX)")]
		public string DAILIJGYHZH
		{
			get
			{
				return this._DAILIJGYHZH;
			}
			set
			{
				if ((this._DAILIJGYHZH != value))
				{
					this._DAILIJGYHZH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGMC", DbType="NVarChar(MAX)")]
		public string DAILIJGMC
		{
			get
			{
				return this._DAILIJGMC;
			}
			set
			{
				if ((this._DAILIJGMC != value))
				{
					this._DAILIJGMC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGFZRXM", DbType="NVarChar(MAX)")]
		public string DAILIJGFZRXM
		{
			get
			{
				return this._DAILIJGFZRXM;
			}
			set
			{
				if ((this._DAILIJGFZRXM != value))
				{
					this._DAILIJGFZRXM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGBZH", DbType="NVarChar(MAX)")]
		public string DAILIJGBZH
		{
			get
			{
				return this._DAILIJGBZH;
			}
			set
			{
				if ((this._DAILIJGBZH != value))
				{
					this._DAILIJGBZH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGBZS", DbType="NVarChar(MAX)")]
		public string DAILIJGBZS
		{
			get
			{
				return this._DAILIJGBZS;
			}
			set
			{
				if ((this._DAILIJGBZS != value))
				{
					this._DAILIJGBZS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHANGJIZGDW", DbType="NVarChar(MAX)")]
		public string SHANGJIZGDW
		{
			get
			{
				return this._SHANGJIZGDW;
			}
			set
			{
				if ((this._SHANGJIZGDW != value))
				{
					this._SHANGJIZGDW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIBIANDW", DbType="NVarChar(MAX)")]
		public string PIBIANDW
		{
			get
			{
				return this._PIBIANDW;
			}
			set
			{
				if ((this._PIBIANDW != value))
				{
					this._PIBIANDW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONGSDJBJ", DbType="NVarChar(MAX)")]
		public string GONGSDJBJ
		{
			get
			{
				return this._GONGSDJBJ;
			}
			set
			{
				if ((this._GONGSDJBJ != value))
				{
					this._GONGSDJBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZHUANLIDJRQ", DbType="NVarChar(255)")]
		public string ZHUANLIDJRQ
		{
			get
			{
				return this._ZHUANLIDJRQ;
			}
			set
			{
				if ((this._ZHUANLIDJRQ != value))
				{
					this._ZHUANLIDJRQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENGJIRQ", DbType="NVarChar(255)")]
		public string DENGJIRQ
		{
			get
			{
				return this._DENGJIRQ;
			}
			set
			{
				if ((this._DENGJIRQ != value))
				{
					this._DENGJIRQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JINGJIXZ", DbType="NVarChar(MAX)")]
		public string JINGJIXZ
		{
			get
			{
				return this._JINGJIXZ;
			}
			set
			{
				if ((this._JINGJIXZ != value))
				{
					this._JINGJIXZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGZT", DbType="NVarChar(MAX)")]
		public string DAILIJGZT
		{
			get
			{
				return this._DAILIJGZT;
			}
			set
			{
				if ((this._DAILIJGZT != value))
				{
					this._DAILIJGZT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUOZAIDQ", DbType="NVarChar(MAX)")]
		public string SUOZAIDQ
		{
			get
			{
				return this._SUOZAIDQ;
			}
			set
			{
				if ((this._SUOZAIDQ != value))
				{
					this._SUOZAIDQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JINGYINGFW", DbType="NVarChar(MAX)")]
		public string JINGYINGFW
		{
			get
			{
				return this._JINGYINGFW;
			}
			set
			{
				if ((this._JINGYINGFW != value))
				{
					this._JINGYINGFW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHEWAIQBJ", DbType="NVarChar(MAX)")]
		public string SHEWAIQBJ
		{
			get
			{
				return this._SHEWAIQBJ;
			}
			set
			{
				if ((this._SHEWAIQBJ != value))
				{
					this._SHEWAIQBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGJC", DbType="NVarChar(MAX)")]
		public string DAILIJGJC
		{
			get
			{
				return this._DAILIJGJC;
			}
			set
			{
				if ((this._DAILIJGJC != value))
				{
					this._DAILIJGJC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEZIQXJBJ", DbType="NVarChar(MAX)")]
		public string KEZIQXJBJ
		{
			get
			{
				return this._KEZIQXJBJ;
			}
			set
			{
				if ((this._KEZIQXJBJ != value))
				{
					this._KEZIQXJBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIANGENGBJ", DbType="NVarChar(MAX)")]
		public string BIANGENGBJ
		{
			get
			{
				return this._BIANGENGBJ;
			}
			set
			{
				if ((this._BIANGENGBJ != value))
				{
					this._BIANGENGBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGNAME", DbType="NVarChar(MAX)")]
		public string REGNAME
		{
			get
			{
				return this._REGNAME;
			}
			set
			{
				if ((this._REGNAME != value))
				{
					this._REGNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGTIME", DbType="NVarChar(MAX)")]
		public string REGTIME
		{
			get
			{
				return this._REGTIME;
			}
			set
			{
				if ((this._REGTIME != value))
				{
					this._REGTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODNAME", DbType="NVarChar(MAX)")]
		public string MODNAME
		{
			get
			{
				return this._MODNAME;
			}
			set
			{
				if ((this._MODNAME != value))
				{
					this._MODNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODTIME", DbType="NVarChar(MAX)")]
		public string MODTIME
		{
			get
			{
				return this._MODTIME;
			}
			set
			{
				if ((this._MODTIME != value))
				{
					this._MODTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YOUXIAOBJ", DbType="NVarChar(MAX)")]
		public string YOUXIAOBJ
		{
			get
			{
				return this._YOUXIAOBJ;
			}
			set
			{
				if ((this._YOUXIAOBJ != value))
				{
					this._YOUXIAOBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIANJIANZT", DbType="NVarChar(MAX)")]
		public string NIANJIANZT
		{
			get
			{
				return this._NIANJIANZT;
			}
			set
			{
				if ((this._NIANJIANZT != value))
				{
					this._NIANJIANZT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAILIJGYDDH", DbType="NVarChar(MAX)")]
		public string DAILIJGYDDH
		{
			get
			{
				return this._DAILIJGYDDH;
			}
			set
			{
				if ((this._DAILIJGYDDH != value))
				{
					this._DAILIJGYDDH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHENGJIECXGDQ", DbType="NVarChar(MAX)")]
		public string CHENGJIECXGDQ
		{
			get
			{
				return this._CHENGJIECXGDQ;
			}
			set
			{
				if ((this._CHENGJIECXGDQ != value))
				{
					this._CHENGJIECXGDQ = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
