#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpic.Cprs2010.Cfg
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LegalStatus")]
	public partial class CfgLegalStatusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCnLegalStatus(CnLegalStatus instance);
    partial void UpdateCnLegalStatus(CnLegalStatus instance);
    partial void DeleteCnLegalStatus(CnLegalStatus instance);
    #endregion
		
		public CfgLegalStatusDataContext() : 
				base(global::Cpic.Cprs2010.Cfg.Properties.Settings.Default.LegalStatusConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CfgLegalStatusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgLegalStatusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgLegalStatusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CfgLegalStatusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CnLegalStatus> CnLegalStatus
		{
			get
			{
				return this.GetTable<CnLegalStatus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CnLegalStatus")]
	public partial class CnLegalStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _AppNo;
		
		private string _LegalDate;
		
		private string _LegalCode;
		
		private string _InidCode;
		
		private string _OldInid;
		
		private string _NewInid;
		
		private string _Tfile;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnAppNoChanging(string value);
    partial void OnAppNoChanged();
    partial void OnLegalDateChanging(string value);
    partial void OnLegalDateChanged();
    partial void OnLegalCodeChanging(string value);
    partial void OnLegalCodeChanged();
    partial void OnInidCodeChanging(string value);
    partial void OnInidCodeChanged();
    partial void OnOldInidChanging(string value);
    partial void OnOldInidChanged();
    partial void OnNewInidChanging(string value);
    partial void OnNewInidChanged();
    partial void OnTfileChanging(string value);
    partial void OnTfileChanged();
    #endregion
		
		public CnLegalStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppNo", DbType="VarChar(50)")]
		public string AppNo
		{
			get
			{
				return this._AppNo;
			}
			set
			{
				if ((this._AppNo != value))
				{
					this.OnAppNoChanging(value);
					this.SendPropertyChanging();
					this._AppNo = value;
					this.SendPropertyChanged("AppNo");
					this.OnAppNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalDate", DbType="VarChar(50)")]
		public string LegalDate
		{
			get
			{
				return this._LegalDate;
			}
			set
			{
				if ((this._LegalDate != value))
				{
					this.OnLegalDateChanging(value);
					this.SendPropertyChanging();
					this._LegalDate = value;
					this.SendPropertyChanged("LegalDate");
					this.OnLegalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalCode", DbType="VarChar(50)")]
		public string LegalCode
		{
			get
			{
				return this._LegalCode;
			}
			set
			{
				if ((this._LegalCode != value))
				{
					this.OnLegalCodeChanging(value);
					this.SendPropertyChanging();
					this._LegalCode = value;
					this.SendPropertyChanged("LegalCode");
					this.OnLegalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InidCode", DbType="VarChar(50)")]
		public string InidCode
		{
			get
			{
				return this._InidCode;
			}
			set
			{
				if ((this._InidCode != value))
				{
					this.OnInidCodeChanging(value);
					this.SendPropertyChanging();
					this._InidCode = value;
					this.SendPropertyChanged("InidCode");
					this.OnInidCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldInid", DbType="VarChar(MAX)")]
		public string OldInid
		{
			get
			{
				return this._OldInid;
			}
			set
			{
				if ((this._OldInid != value))
				{
					this.OnOldInidChanging(value);
					this.SendPropertyChanging();
					this._OldInid = value;
					this.SendPropertyChanged("OldInid");
					this.OnOldInidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewInid", DbType="VarChar(MAX)")]
		public string NewInid
		{
			get
			{
				return this._NewInid;
			}
			set
			{
				if ((this._NewInid != value))
				{
					this.OnNewInidChanging(value);
					this.SendPropertyChanging();
					this._NewInid = value;
					this.SendPropertyChanged("NewInid");
					this.OnNewInidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tfile", DbType="VarChar(100)")]
		public string Tfile
		{
			get
			{
				return this._Tfile;
			}
			set
			{
				if ((this._Tfile != value))
				{
					this.OnTfileChanging(value);
					this.SendPropertyChanging();
					this._Tfile = value;
					this.SendPropertyChanged("Tfile");
					this.OnTfileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
