#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PatentQuery")]
	public partial class PQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTLC_Albums(TLC_Albums instance);
    partial void UpdateTLC_Albums(TLC_Albums instance);
    partial void DeleteTLC_Albums(TLC_Albums instance);
    partial void InsertTLC_Collects(TLC_Collects instance);
    partial void UpdateTLC_Collects(TLC_Collects instance);
    partial void DeleteTLC_Collects(TLC_Collects instance);
    partial void InsertsysTree(sysTree instance);
    partial void UpdatesysTree(sysTree instance);
    partial void DeletesysTree(sysTree instance);
    partial void InsertztTree(ztTree instance);
    partial void UpdateztTree(ztTree instance);
    partial void DeleteztTree(ztTree instance);
    partial void Insertztsp(ztsp instance);
    partial void Updateztsp(ztsp instance);
    partial void Deleteztsp(ztsp instance);
    partial void InsertZtDbList(ZtDbList instance);
    partial void UpdateZtDbList(ZtDbList instance);
    partial void DeleteZtDbList(ZtDbList instance);
    partial void Insertztdb(ztdb instance);
    partial void Updateztdb(ztdb instance);
    partial void Deleteztdb(ztdb instance);
    #endregion
		
		public PQDataContext() : 
				base(global::TLC.Properties.Settings.Default.PatentQueryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TLC_Albums> TLC_Albums
		{
			get
			{
				return this.GetTable<TLC_Albums>();
			}
		}
		
		public System.Data.Linq.Table<TLC_Collects> TLC_Collects
		{
			get
			{
				return this.GetTable<TLC_Collects>();
			}
		}
		
		public System.Data.Linq.Table<sysTree> sysTree
		{
			get
			{
				return this.GetTable<sysTree>();
			}
		}
		
		public System.Data.Linq.Table<ztTree> ztTree
		{
			get
			{
				return this.GetTable<ztTree>();
			}
		}
		
		public System.Data.Linq.Table<ztsp> ztsp
		{
			get
			{
				return this.GetTable<ztsp>();
			}
		}
		
		public System.Data.Linq.Table<ZtDbList> ZtDbList
		{
			get
			{
				return this.GetTable<ZtDbList>();
			}
		}
		
		public System.Data.Linq.Table<ztdb> ztdb
		{
			get
			{
				return this.GetTable<ztdb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TLC_Albums")]
	public partial class TLC_Albums : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlbumId;
		
		private int _UserId;
		
		private int _ParentId;
		
		private string _Title;
		
		private string _Note;
		
		private int _Collects;
		
		private int _Orders;
		
		private System.Nullable<byte> _live;
		
		private System.Nullable<bool> _isdel;
		
		private System.Nullable<byte> _IsParent;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlbumIdChanging(int value);
    partial void OnAlbumIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnParentIdChanging(int value);
    partial void OnParentIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnCollectsChanging(int value);
    partial void OnCollectsChanged();
    partial void OnOrdersChanging(int value);
    partial void OnOrdersChanged();
    partial void OnliveChanging(System.Nullable<byte> value);
    partial void OnliveChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    partial void OnIsParentChanging(System.Nullable<byte> value);
    partial void OnIsParentChanged();
    #endregion
		
		public TLC_Albums()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AlbumId
		{
			get
			{
				return this._AlbumId;
			}
			set
			{
				if ((this._AlbumId != value))
				{
					this.OnAlbumIdChanging(value);
					this.SendPropertyChanging();
					this._AlbumId = value;
					this.SendPropertyChanged("AlbumId");
					this.OnAlbumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int NOT NULL")]
		public int ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(255)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collects", DbType="Int NOT NULL")]
		public int Collects
		{
			get
			{
				return this._Collects;
			}
			set
			{
				if ((this._Collects != value))
				{
					this.OnCollectsChanging(value);
					this.SendPropertyChanging();
					this._Collects = value;
					this.SendPropertyChanged("Collects");
					this.OnCollectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orders", DbType="Int NOT NULL")]
		public int Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				if ((this._Orders != value))
				{
					this.OnOrdersChanging(value);
					this.SendPropertyChanging();
					this._Orders = value;
					this.SendPropertyChanged("Orders");
					this.OnOrdersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live", DbType="TinyInt")]
		public System.Nullable<byte> live
		{
			get
			{
				return this._live;
			}
			set
			{
				if ((this._live != value))
				{
					this.OnliveChanging(value);
					this.SendPropertyChanging();
					this._live = value;
					this.SendPropertyChanged("live");
					this.OnliveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="TinyInt")]
		public System.Nullable<byte> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TLC_Collects")]
	public partial class TLC_Collects : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CollectId;
		
		private int _UserId;
		
		private int _AlbumId;
		
		private byte _Types;
		
		private System.Nullable<int> _Pid;
		
		private string _AppNo;
		
		private string _Title;
		
		private string _Number;
		
		private byte _LawState;
		
		private System.Nullable<System.DateTime> _CollectDate;
		
		private string _Note;
		
		private System.Nullable<System.DateTime> _NoteDate;
		
		private string _Type;
		
		private System.Nullable<bool> _isdel;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCollectIdChanging(int value);
    partial void OnCollectIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnAlbumIdChanging(int value);
    partial void OnAlbumIdChanged();
    partial void OnTypesChanging(byte value);
    partial void OnTypesChanged();
    partial void OnPidChanging(System.Nullable<int> value);
    partial void OnPidChanged();
    partial void OnAppNoChanging(string value);
    partial void OnAppNoChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnLawStateChanging(byte value);
    partial void OnLawStateChanged();
    partial void OnCollectDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCollectDateChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnNoteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNoteDateChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    #endregion
		
		public TLC_Collects()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CollectId
		{
			get
			{
				return this._CollectId;
			}
			set
			{
				if ((this._CollectId != value))
				{
					this.OnCollectIdChanging(value);
					this.SendPropertyChanging();
					this._CollectId = value;
					this.SendPropertyChanged("CollectId");
					this.OnCollectIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumId", DbType="Int NOT NULL")]
		public int AlbumId
		{
			get
			{
				return this._AlbumId;
			}
			set
			{
				if ((this._AlbumId != value))
				{
					this.OnAlbumIdChanging(value);
					this.SendPropertyChanging();
					this._AlbumId = value;
					this.SendPropertyChanged("AlbumId");
					this.OnAlbumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Types", DbType="TinyInt NOT NULL")]
		public byte Types
		{
			get
			{
				return this._Types;
			}
			set
			{
				if ((this._Types != value))
				{
					this.OnTypesChanging(value);
					this.SendPropertyChanging();
					this._Types = value;
					this.SendPropertyChanged("Types");
					this.OnTypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int")]
		public System.Nullable<int> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppNo", DbType="VarChar(25)")]
		public string AppNo
		{
			get
			{
				return this._AppNo;
			}
			set
			{
				if ((this._AppNo != value))
				{
					this.OnAppNoChanging(value);
					this.SendPropertyChanging();
					this._AppNo = value;
					this.SendPropertyChanged("AppNo");
					this.OnAppNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(100)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LawState", DbType="TinyInt NOT NULL")]
		public byte LawState
		{
			get
			{
				return this._LawState;
			}
			set
			{
				if ((this._LawState != value))
				{
					this.OnLawStateChanging(value);
					this.SendPropertyChanging();
					this._LawState = value;
					this.SendPropertyChanged("LawState");
					this.OnLawStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CollectDate
		{
			get
			{
				return this._CollectDate;
			}
			set
			{
				if ((this._CollectDate != value))
				{
					this.OnCollectDateChanging(value);
					this.SendPropertyChanging();
					this._CollectDate = value;
					this.SendPropertyChanged("CollectDate");
					this.OnCollectDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(4000)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NoteDate
		{
			get
			{
				return this._NoteDate;
			}
			set
			{
				if ((this._NoteDate != value))
				{
					this.OnNoteDateChanging(value);
					this.SendPropertyChanging();
					this._NoteDate = value;
					this.SendPropertyChanged("NoteDate");
					this.OnNoteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Char(2)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sysTree")]
	public partial class sysTree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NodeId;
		
		private string _NodeName;
		
		private System.Nullable<int> _PNodeid;
		
		private System.Nullable<bool> _IsParent;
		
		private string _type;
		
		private System.Nullable<bool> _isdel;
		
		private string _des;
		
		private System.Nullable<byte> _live;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNodeIdChanging(int value);
    partial void OnNodeIdChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnPNodeidChanging(System.Nullable<int> value);
    partial void OnPNodeidChanged();
    partial void OnIsParentChanging(System.Nullable<bool> value);
    partial void OnIsParentChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    partial void OndesChanging(string value);
    partial void OndesChanged();
    partial void OnliveChanging(System.Nullable<byte> value);
    partial void OnliveChanged();
    #endregion
		
		public sysTree()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(400)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this.OnNodeNameChanging(value);
					this.SendPropertyChanging();
					this._NodeName = value;
					this.SendPropertyChanged("NodeName");
					this.OnNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNodeid", DbType="Int")]
		public System.Nullable<int> PNodeid
		{
			get
			{
				return this._PNodeid;
			}
			set
			{
				if ((this._PNodeid != value))
				{
					this.OnPNodeidChanging(value);
					this.SendPropertyChanging();
					this._PNodeid = value;
					this.SendPropertyChanged("PNodeid");
					this.OnPNodeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(10)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des", DbType="NVarChar(1000)")]
		public string des
		{
			get
			{
				return this._des;
			}
			set
			{
				if ((this._des != value))
				{
					this.OndesChanging(value);
					this.SendPropertyChanging();
					this._des = value;
					this.SendPropertyChanged("des");
					this.OndesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live", DbType="TinyInt")]
		public System.Nullable<byte> live
		{
			get
			{
				return this._live;
			}
			set
			{
				if ((this._live != value))
				{
					this.OnliveChanging(value);
					this.SendPropertyChanging();
					this._live = value;
					this.SendPropertyChanged("live");
					this.OnliveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ztTree")]
	public partial class ztTree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NodeId;
		
		private string _NodeName;
		
		private System.Nullable<int> _PNodeid;
		
		private System.Nullable<byte> _IsParent;
		
		private System.Nullable<int> _thId;
		
		private string _type;
		
		private System.Nullable<int> _CreateUserId;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<bool> _isdel;
		
		private string _des;
		
		private System.Nullable<byte> _live;
		
		private string _Nid;
		
		private string _PNid;
		
		private string _zid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNodeIdChanging(int value);
    partial void OnNodeIdChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnPNodeidChanging(System.Nullable<int> value);
    partial void OnPNodeidChanged();
    partial void OnIsParentChanging(System.Nullable<byte> value);
    partial void OnIsParentChanged();
    partial void OnthIdChanging(System.Nullable<int> value);
    partial void OnthIdChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnCreateUserIdChanging(System.Nullable<int> value);
    partial void OnCreateUserIdChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    partial void OndesChanging(string value);
    partial void OndesChanged();
    partial void OnliveChanging(System.Nullable<byte> value);
    partial void OnliveChanged();
    partial void OnNidChanging(string value);
    partial void OnNidChanged();
    partial void OnPNidChanging(string value);
    partial void OnPNidChanged();
    partial void OnzidChanging(string value);
    partial void OnzidChanged();
    #endregion
		
		public ztTree()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="NVarChar(40)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this.OnNodeNameChanging(value);
					this.SendPropertyChanging();
					this._NodeName = value;
					this.SendPropertyChanged("NodeName");
					this.OnNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNodeid", DbType="Int")]
		public System.Nullable<int> PNodeid
		{
			get
			{
				return this._PNodeid;
			}
			set
			{
				if ((this._PNodeid != value))
				{
					this.OnPNodeidChanging(value);
					this.SendPropertyChanging();
					this._PNodeid = value;
					this.SendPropertyChanged("PNodeid");
					this.OnPNodeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="TinyInt")]
		public System.Nullable<byte> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thId", DbType="Int")]
		public System.Nullable<int> thId
		{
			get
			{
				return this._thId;
			}
			set
			{
				if ((this._thId != value))
				{
					this.OnthIdChanging(value);
					this.SendPropertyChanging();
					this._thId = value;
					this.SendPropertyChanged("thId");
					this.OnthIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(10)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserId", DbType="Int")]
		public System.Nullable<int> CreateUserId
		{
			get
			{
				return this._CreateUserId;
			}
			set
			{
				if ((this._CreateUserId != value))
				{
					this.OnCreateUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreateUserId = value;
					this.SendPropertyChanged("CreateUserId");
					this.OnCreateUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des", DbType="NVarChar(1000)")]
		public string des
		{
			get
			{
				return this._des;
			}
			set
			{
				if ((this._des != value))
				{
					this.OndesChanging(value);
					this.SendPropertyChanging();
					this._des = value;
					this.SendPropertyChanged("des");
					this.OndesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live", DbType="TinyInt")]
		public System.Nullable<byte> live
		{
			get
			{
				return this._live;
			}
			set
			{
				if ((this._live != value))
				{
					this.OnliveChanging(value);
					this.SendPropertyChanging();
					this._live = value;
					this.SendPropertyChanged("live");
					this.OnliveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nid", DbType="Char(36)")]
		public string Nid
		{
			get
			{
				return this._Nid;
			}
			set
			{
				if ((this._Nid != value))
				{
					this.OnNidChanging(value);
					this.SendPropertyChanging();
					this._Nid = value;
					this.SendPropertyChanged("Nid");
					this.OnNidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNid", DbType="Char(36)")]
		public string PNid
		{
			get
			{
				return this._PNid;
			}
			set
			{
				if ((this._PNid != value))
				{
					this.OnPNidChanging(value);
					this.SendPropertyChanging();
					this._PNid = value;
					this.SendPropertyChanged("PNid");
					this.OnPNidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zid", DbType="VarChar(36)")]
		public string zid
		{
			get
			{
				return this._zid;
			}
			set
			{
				if ((this._zid != value))
				{
					this.OnzidChanging(value);
					this.SendPropertyChanging();
					this._zid = value;
					this.SendPropertyChanged("zid");
					this.OnzidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ztsp")]
	public partial class ztsp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _NodeId;
		
		private string _NodeName;
		
		private System.Nullable<int> _SPNum;
		
		private string _sp;
		
		private System.Nullable<int> _Hit;
		
		private System.Nullable<int> _UpdateSum;
		
		private System.Nullable<bool> _isAutoUpdate;
		
		private string _Type;
		
		private System.Nullable<bool> _isUsed;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<int> _CreateUserId;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<byte> _isdel;
		
		private System.Nullable<int> _ztid;
		
		private string _st;
		
		private string _Nid;
		
		private string _zid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNodeIdChanging(System.Nullable<int> value);
    partial void OnNodeIdChanged();
    partial void OnNodeNameChanging(string value);
    partial void OnNodeNameChanged();
    partial void OnSPNumChanging(System.Nullable<int> value);
    partial void OnSPNumChanged();
    partial void OnspChanging(string value);
    partial void OnspChanged();
    partial void OnHitChanging(System.Nullable<int> value);
    partial void OnHitChanged();
    partial void OnUpdateSumChanging(System.Nullable<int> value);
    partial void OnUpdateSumChanged();
    partial void OnisAutoUpdateChanging(System.Nullable<bool> value);
    partial void OnisAutoUpdateChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnisUsedChanging(System.Nullable<bool> value);
    partial void OnisUsedChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnCreateUserIdChanging(System.Nullable<int> value);
    partial void OnCreateUserIdChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnisdelChanging(System.Nullable<byte> value);
    partial void OnisdelChanged();
    partial void OnztidChanging(System.Nullable<int> value);
    partial void OnztidChanged();
    partial void OnstChanging(string value);
    partial void OnstChanged();
    partial void OnNidChanging(string value);
    partial void OnNidChanged();
    partial void OnzidChanging(string value);
    partial void OnzidChanged();
    #endregion
		
		public ztsp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", DbType="Int")]
		public System.Nullable<int> NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", DbType="VarChar(50)")]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this.OnNodeNameChanging(value);
					this.SendPropertyChanging();
					this._NodeName = value;
					this.SendPropertyChanged("NodeName");
					this.OnNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPNum", DbType="Int")]
		public System.Nullable<int> SPNum
		{
			get
			{
				return this._SPNum;
			}
			set
			{
				if ((this._SPNum != value))
				{
					this.OnSPNumChanging(value);
					this.SendPropertyChanging();
					this._SPNum = value;
					this.SendPropertyChanged("SPNum");
					this.OnSPNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp", DbType="VarChar(1200) NOT NULL", CanBeNull=false)]
		public string sp
		{
			get
			{
				return this._sp;
			}
			set
			{
				if ((this._sp != value))
				{
					this.OnspChanging(value);
					this.SendPropertyChanging();
					this._sp = value;
					this.SendPropertyChanged("sp");
					this.OnspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hit", DbType="Int")]
		public System.Nullable<int> Hit
		{
			get
			{
				return this._Hit;
			}
			set
			{
				if ((this._Hit != value))
				{
					this.OnHitChanging(value);
					this.SendPropertyChanging();
					this._Hit = value;
					this.SendPropertyChanged("Hit");
					this.OnHitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateSum", DbType="Int")]
		public System.Nullable<int> UpdateSum
		{
			get
			{
				return this._UpdateSum;
			}
			set
			{
				if ((this._UpdateSum != value))
				{
					this.OnUpdateSumChanging(value);
					this.SendPropertyChanging();
					this._UpdateSum = value;
					this.SendPropertyChanged("UpdateSum");
					this.OnUpdateSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAutoUpdate", DbType="Bit")]
		public System.Nullable<bool> isAutoUpdate
		{
			get
			{
				return this._isAutoUpdate;
			}
			set
			{
				if ((this._isAutoUpdate != value))
				{
					this.OnisAutoUpdateChanging(value);
					this.SendPropertyChanging();
					this._isAutoUpdate = value;
					this.SendPropertyChanged("isAutoUpdate");
					this.OnisAutoUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isUsed", DbType="Bit")]
		public System.Nullable<bool> isUsed
		{
			get
			{
				return this._isUsed;
			}
			set
			{
				if ((this._isUsed != value))
				{
					this.OnisUsedChanging(value);
					this.SendPropertyChanging();
					this._isUsed = value;
					this.SendPropertyChanged("isUsed");
					this.OnisUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserId", DbType="Int")]
		public System.Nullable<int> CreateUserId
		{
			get
			{
				return this._CreateUserId;
			}
			set
			{
				if ((this._CreateUserId != value))
				{
					this.OnCreateUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreateUserId = value;
					this.SendPropertyChanged("CreateUserId");
					this.OnCreateUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="TinyInt")]
		public System.Nullable<byte> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztid", DbType="Int")]
		public System.Nullable<int> ztid
		{
			get
			{
				return this._ztid;
			}
			set
			{
				if ((this._ztid != value))
				{
					this.OnztidChanging(value);
					this.SendPropertyChanging();
					this._ztid = value;
					this.SendPropertyChanged("ztid");
					this.OnztidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st", DbType="VarChar(20)")]
		public string st
		{
			get
			{
				return this._st;
			}
			set
			{
				if ((this._st != value))
				{
					this.OnstChanging(value);
					this.SendPropertyChanging();
					this._st = value;
					this.SendPropertyChanged("st");
					this.OnstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nid", DbType="Char(36)")]
		public string Nid
		{
			get
			{
				return this._Nid;
			}
			set
			{
				if ((this._Nid != value))
				{
					this.OnNidChanging(value);
					this.SendPropertyChanging();
					this._Nid = value;
					this.SendPropertyChanged("Nid");
					this.OnNidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zid", DbType="VarChar(36)")]
		public string zid
		{
			get
			{
				return this._zid;
			}
			set
			{
				if ((this._zid != value))
				{
					this.OnzidChanging(value);
					this.SendPropertyChanging();
					this._zid = value;
					this.SendPropertyChanged("zid");
					this.OnzidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZtDbList")]
	public partial class ZtDbList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DbID;
		
		private string _ztDbName;
		
		private System.Nullable<int> _dbType;
		
		private System.Nullable<int> _CreateUserId;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private string _DbDes;
		
		private System.Nullable<bool> _IsDel;
		
		private string _ztHeardImg;
		
		private string _zid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDbIDChanging(int value);
    partial void OnDbIDChanged();
    partial void OnztDbNameChanging(string value);
    partial void OnztDbNameChanged();
    partial void OndbTypeChanging(System.Nullable<int> value);
    partial void OndbTypeChanged();
    partial void OnCreateUserIdChanging(System.Nullable<int> value);
    partial void OnCreateUserIdChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnDbDesChanging(string value);
    partial void OnDbDesChanged();
    partial void OnIsDelChanging(System.Nullable<bool> value);
    partial void OnIsDelChanged();
    partial void OnztHeardImgChanging(string value);
    partial void OnztHeardImgChanged();
    partial void OnzidChanging(string value);
    partial void OnzidChanged();
    #endregion
		
		public ZtDbList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DbID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DbID
		{
			get
			{
				return this._DbID;
			}
			set
			{
				if ((this._DbID != value))
				{
					this.OnDbIDChanging(value);
					this.SendPropertyChanging();
					this._DbID = value;
					this.SendPropertyChanged("DbID");
					this.OnDbIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztDbName", DbType="NVarChar(20)")]
		public string ztDbName
		{
			get
			{
				return this._ztDbName;
			}
			set
			{
				if ((this._ztDbName != value))
				{
					this.OnztDbNameChanging(value);
					this.SendPropertyChanging();
					this._ztDbName = value;
					this.SendPropertyChanged("ztDbName");
					this.OnztDbNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbType", DbType="Int")]
		public System.Nullable<int> dbType
		{
			get
			{
				return this._dbType;
			}
			set
			{
				if ((this._dbType != value))
				{
					this.OndbTypeChanging(value);
					this.SendPropertyChanging();
					this._dbType = value;
					this.SendPropertyChanged("dbType");
					this.OndbTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserId", DbType="Int")]
		public System.Nullable<int> CreateUserId
		{
			get
			{
				return this._CreateUserId;
			}
			set
			{
				if ((this._CreateUserId != value))
				{
					this.OnCreateUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreateUserId = value;
					this.SendPropertyChanged("CreateUserId");
					this.OnCreateUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DbDes", DbType="VarChar(500)")]
		public string DbDes
		{
			get
			{
				return this._DbDes;
			}
			set
			{
				if ((this._DbDes != value))
				{
					this.OnDbDesChanging(value);
					this.SendPropertyChanging();
					this._DbDes = value;
					this.SendPropertyChanged("DbDes");
					this.OnDbDesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Bit")]
		public System.Nullable<bool> IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this.OnIsDelChanging(value);
					this.SendPropertyChanging();
					this._IsDel = value;
					this.SendPropertyChanged("IsDel");
					this.OnIsDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztHeardImg", DbType="VarChar(45)")]
		public string ztHeardImg
		{
			get
			{
				return this._ztHeardImg;
			}
			set
			{
				if ((this._ztHeardImg != value))
				{
					this.OnztHeardImgChanging(value);
					this.SendPropertyChanging();
					this._ztHeardImg = value;
					this.SendPropertyChanged("ztHeardImg");
					this.OnztHeardImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zid", DbType="VarChar(36)")]
		public string zid
		{
			get
			{
				return this._zid;
			}
			set
			{
				if ((this._zid != value))
				{
					this.OnzidChanging(value);
					this.SendPropertyChanging();
					this._zid = value;
					this.SendPropertyChanged("zid");
					this.OnzidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ztdb")]
	public partial class ztdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _NodeId;
		
		private System.Nullable<int> _Pid;
		
		private System.Nullable<byte> _Iscore;
		
		private System.Nullable<bool> _isUpdate;
		
		private string _Form;
		
		private string _type;
		
		private System.Nullable<int> _CreateUserId;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<bool> _isdel;
		
		private string _nid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNodeIdChanging(System.Nullable<int> value);
    partial void OnNodeIdChanged();
    partial void OnPidChanging(System.Nullable<int> value);
    partial void OnPidChanged();
    partial void OnIscoreChanging(System.Nullable<byte> value);
    partial void OnIscoreChanged();
    partial void OnisUpdateChanging(System.Nullable<bool> value);
    partial void OnisUpdateChanged();
    partial void OnFormChanging(string value);
    partial void OnFormChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnCreateUserIdChanging(System.Nullable<int> value);
    partial void OnCreateUserIdChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    partial void OnnidChanging(string value);
    partial void OnnidChanged();
    #endregion
		
		public ztdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", DbType="Int")]
		public System.Nullable<int> NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int")]
		public System.Nullable<int> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iscore", DbType="TinyInt")]
		public System.Nullable<byte> Iscore
		{
			get
			{
				return this._Iscore;
			}
			set
			{
				if ((this._Iscore != value))
				{
					this.OnIscoreChanging(value);
					this.SendPropertyChanging();
					this._Iscore = value;
					this.SendPropertyChanged("Iscore");
					this.OnIscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isUpdate", DbType="Bit")]
		public System.Nullable<bool> isUpdate
		{
			get
			{
				return this._isUpdate;
			}
			set
			{
				if ((this._isUpdate != value))
				{
					this.OnisUpdateChanging(value);
					this.SendPropertyChanging();
					this._isUpdate = value;
					this.SendPropertyChanged("isUpdate");
					this.OnisUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="VarChar(20)")]
		public string Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(10)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserId", DbType="Int")]
		public System.Nullable<int> CreateUserId
		{
			get
			{
				return this._CreateUserId;
			}
			set
			{
				if ((this._CreateUserId != value))
				{
					this.OnCreateUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreateUserId = value;
					this.SendPropertyChanged("CreateUserId");
					this.OnCreateUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit")]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nid", DbType="Char(36)")]
		public string nid
		{
			get
			{
				return this._nid;
			}
			set
			{
				if ((this._nid != value))
				{
					this.OnnidChanging(value);
					this.SendPropertyChanging();
					this._nid = value;
					this.SendPropertyChanged("nid");
					this.OnnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
