//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchInterface.WSFLZT {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFLZT.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCnLegal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegalStatus[] GetCnLegal(string sAppno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCnLegalDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegalStatus[] GetCnLegalDetail(string sAppno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCnLegalDetailByAppNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCnLegalDetailByAppNo(string sAppno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFaLvZT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SearchInterface.WSFLZT.ResultInfo QueryFaLvZT(string AppNo, string GongGaoR, string FaLvZT, string ZhuanLiQR, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFaLvZTGetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegalStatus[] QueryFaLvZTGetList(string SearchNo, int PageIndex, int PageSize, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryZhuanYi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegal012[] QueryZhuanYi(out int pagCount, string AppNo, string IPC, string DengJISXR, string BianGengQQLR, string BianGengHQLR, string BianGengQDZ, string BianGengHDZ, int pagIndex, int pagSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryZhiYa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegal015[] QueryZhiYa(out int pagCount, string AppNo, string IPC, string HeTongZT, string DengJiSXR, string BianGengR, string JieChuR, string DengJiH, string CHuZhiR, string ZhiQuanR, int pagIndex, int pagSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryShiShiXuKe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CnLegal014[] QueryShiShiXuKe(out int pagCount, string AppNo, string IPC, string XuKeZL, string HeTongZT, string BeiAnRQ, string BianGengR, string JIeChuR, string HeTongBAH, string RangYuR, string SHouRangR, int pagIndex, int pagSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFaLvZhuangTai", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TbCnLegalStatusNew[] QueryFaLvZhuangTai(out int pagCount, string AppNo, string LegalDate, string LegalStatusInfo, string ShenQingRenAppNo, int pagIndex, int pagSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFaLvZhuangTaiSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getFaLvZhuangTaiSimple(string AppNo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegalStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string vOLField;
        
        private string nUMField;
        
        private string pAGField;
        
        private string iPCField;
        
        private string sHENQINGHField;
        
        private string sHENQINGRField;
        
        private string sHENQINGGBRField;
        
        private string sHOUQUANGGRField;
        
        private string wUXIAOXGJDHField;
        
        private string wUXIAOXGJDRField;
        
        private string zHONGZHIRField;
        
        private string fANGQISXRField;
        
        private string yUANMINGCField;
        
        private string yUANGONGGRField;
        
        private string bIANGENGSXCODEField;
        
        private string bIANGENGSXField;
        
        private string bIANGENGQField;
        
        private string bIANGENGHField;
        
        private string dENGJISXRField;
        
        private string hETONGBAHField;
        
        private string rANGYURField;
        
        private string sHOURANGRField;
        
        private string zHUANLIMCField;
        
        private string xUKEZLField;
        
        private string bEIANRQField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string dENGJIHField;
        
        private string cHUZHIRField;
        
        private string zHIQUANRField;
        
        private string sHOUJIANRField;
        
        private string wENJIANMCField;
        
        private string sourceFileField;
        
        private System.Nullable<System.DateTime> importDataField;
        
        private string dETAILField;
        
        private string dSHENQINGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
                this.RaisePropertyChanged("JUANQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
                this.RaisePropertyChanged("PatentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
                this.RaisePropertyChanged("LegalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
                this.RaisePropertyChanged("LegalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
                this.RaisePropertyChanged("LegalStatusInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
                this.RaisePropertyChanged("LegalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VOL {
            get {
                return this.vOLField;
            }
            set {
                this.vOLField = value;
                this.RaisePropertyChanged("VOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PAG {
            get {
                return this.pAGField;
            }
            set {
                this.pAGField = value;
                this.RaisePropertyChanged("PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
                this.RaisePropertyChanged("IPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
                this.RaisePropertyChanged("SHENQINGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SHENQINGR {
            get {
                return this.sHENQINGRField;
            }
            set {
                this.sHENQINGRField = value;
                this.RaisePropertyChanged("SHENQINGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SHENQINGGBR {
            get {
                return this.sHENQINGGBRField;
            }
            set {
                this.sHENQINGGBRField = value;
                this.RaisePropertyChanged("SHENQINGGBR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SHOUQUANGGR {
            get {
                return this.sHOUQUANGGRField;
            }
            set {
                this.sHOUQUANGGRField = value;
                this.RaisePropertyChanged("SHOUQUANGGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string WUXIAOXGJDH {
            get {
                return this.wUXIAOXGJDHField;
            }
            set {
                this.wUXIAOXGJDHField = value;
                this.RaisePropertyChanged("WUXIAOXGJDH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string WUXIAOXGJDR {
            get {
                return this.wUXIAOXGJDRField;
            }
            set {
                this.wUXIAOXGJDRField = value;
                this.RaisePropertyChanged("WUXIAOXGJDR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ZHONGZHIR {
            get {
                return this.zHONGZHIRField;
            }
            set {
                this.zHONGZHIRField = value;
                this.RaisePropertyChanged("ZHONGZHIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FANGQISXR {
            get {
                return this.fANGQISXRField;
            }
            set {
                this.fANGQISXRField = value;
                this.RaisePropertyChanged("FANGQISXR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string YUANMINGC {
            get {
                return this.yUANMINGCField;
            }
            set {
                this.yUANMINGCField = value;
                this.RaisePropertyChanged("YUANMINGC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string YUANGONGGR {
            get {
                return this.yUANGONGGRField;
            }
            set {
                this.yUANGONGGRField = value;
                this.RaisePropertyChanged("YUANGONGGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BIANGENGSXCODE {
            get {
                return this.bIANGENGSXCODEField;
            }
            set {
                this.bIANGENGSXCODEField = value;
                this.RaisePropertyChanged("BIANGENGSXCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BIANGENGSX {
            get {
                return this.bIANGENGSXField;
            }
            set {
                this.bIANGENGSXField = value;
                this.RaisePropertyChanged("BIANGENGSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string BIANGENGQ {
            get {
                return this.bIANGENGQField;
            }
            set {
                this.bIANGENGQField = value;
                this.RaisePropertyChanged("BIANGENGQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BIANGENGH {
            get {
                return this.bIANGENGHField;
            }
            set {
                this.bIANGENGHField = value;
                this.RaisePropertyChanged("BIANGENGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
                this.RaisePropertyChanged("DENGJISXR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string HETONGBAH {
            get {
                return this.hETONGBAHField;
            }
            set {
                this.hETONGBAHField = value;
                this.RaisePropertyChanged("HETONGBAH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string RANGYUR {
            get {
                return this.rANGYURField;
            }
            set {
                this.rANGYURField = value;
                this.RaisePropertyChanged("RANGYUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SHOURANGR {
            get {
                return this.sHOURANGRField;
            }
            set {
                this.sHOURANGRField = value;
                this.RaisePropertyChanged("SHOURANGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
                this.RaisePropertyChanged("ZHUANLIMC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string XUKEZL {
            get {
                return this.xUKEZLField;
            }
            set {
                this.xUKEZLField = value;
                this.RaisePropertyChanged("XUKEZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string BEIANRQ {
            get {
                return this.bEIANRQField;
            }
            set {
                this.bEIANRQField = value;
                this.RaisePropertyChanged("BEIANRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
                this.RaisePropertyChanged("BIANGENGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
                this.RaisePropertyChanged("JIECHUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string DENGJIH {
            get {
                return this.dENGJIHField;
            }
            set {
                this.dENGJIHField = value;
                this.RaisePropertyChanged("DENGJIH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string CHUZHIR {
            get {
                return this.cHUZHIRField;
            }
            set {
                this.cHUZHIRField = value;
                this.RaisePropertyChanged("CHUZHIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string ZHIQUANR {
            get {
                return this.zHIQUANRField;
            }
            set {
                this.zHIQUANRField = value;
                this.RaisePropertyChanged("ZHIQUANR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string SHOUJIANR {
            get {
                return this.sHOUJIANRField;
            }
            set {
                this.sHOUJIANRField = value;
                this.RaisePropertyChanged("SHOUJIANR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string WENJIANMC {
            get {
                return this.wENJIANMCField;
            }
            set {
                this.wENJIANMCField = value;
                this.RaisePropertyChanged("WENJIANMC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string SourceFile {
            get {
                return this.sourceFileField;
            }
            set {
                this.sourceFileField = value;
                this.RaisePropertyChanged("SourceFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<System.DateTime> ImportData {
            get {
                return this.importDataField;
            }
            set {
                this.importDataField = value;
                this.RaisePropertyChanged("ImportData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
                this.RaisePropertyChanged("DETAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string DSHENQINGH {
            get {
                return this.dSHENQINGHField;
            }
            set {
                this.dSHENQINGHField = value;
                this.RaisePropertyChanged("DSHENQINGH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TbCnLegalStatusNew : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string legalDateField;
        
        private string legalStatusInfoField;
        
        private string detailField;
        
        private string sHENQINGHField;
        
        private string appNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
                this.RaisePropertyChanged("LegalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
                this.RaisePropertyChanged("LegalStatusInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
                this.RaisePropertyChanged("SHENQINGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AppNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
                this.RaisePropertyChanged("AppNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal014 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string xUKEZLField;
        
        private string hETONGZTField;
        
        private string bEIANRQField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string hETONGBAHField;
        
        private string rANGYURField;
        
        private string sHOURANGRField;
        
        private string dETAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
                this.RaisePropertyChanged("JUANQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
                this.RaisePropertyChanged("PatentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
                this.RaisePropertyChanged("LegalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
                this.RaisePropertyChanged("LegalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
                this.RaisePropertyChanged("LegalStatusInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
                this.RaisePropertyChanged("LegalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
                this.RaisePropertyChanged("SHENQINGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
                this.RaisePropertyChanged("ZHUANLIMC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
                this.RaisePropertyChanged("IPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
                this.RaisePropertyChanged("ZHUANLIZY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
                this.RaisePropertyChanged("ZHUANLIZQX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string XUKEZL {
            get {
                return this.xUKEZLField;
            }
            set {
                this.xUKEZLField = value;
                this.RaisePropertyChanged("XUKEZL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string HETONGZT {
            get {
                return this.hETONGZTField;
            }
            set {
                this.hETONGZTField = value;
                this.RaisePropertyChanged("HETONGZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BEIANRQ {
            get {
                return this.bEIANRQField;
            }
            set {
                this.bEIANRQField = value;
                this.RaisePropertyChanged("BEIANRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
                this.RaisePropertyChanged("BIANGENGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
                this.RaisePropertyChanged("JIECHUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string HETONGBAH {
            get {
                return this.hETONGBAHField;
            }
            set {
                this.hETONGBAHField = value;
                this.RaisePropertyChanged("HETONGBAH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string RANGYUR {
            get {
                return this.rANGYURField;
            }
            set {
                this.rANGYURField = value;
                this.RaisePropertyChanged("RANGYUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SHOURANGR {
            get {
                return this.sHOURANGRField;
            }
            set {
                this.sHOURANGRField = value;
                this.RaisePropertyChanged("SHOURANGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
                this.RaisePropertyChanged("DETAIL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal015 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string hETONGZTField;
        
        private string dENGJISXRField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string dENGJIHField;
        
        private string cHUZHIRField;
        
        private string zHIQUANRField;
        
        private string dETAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
                this.RaisePropertyChanged("JUANQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
                this.RaisePropertyChanged("PatentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
                this.RaisePropertyChanged("LegalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
                this.RaisePropertyChanged("LegalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
                this.RaisePropertyChanged("LegalStatusInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
                this.RaisePropertyChanged("LegalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
                this.RaisePropertyChanged("SHENQINGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
                this.RaisePropertyChanged("ZHUANLIMC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
                this.RaisePropertyChanged("IPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
                this.RaisePropertyChanged("ZHUANLIZY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
                this.RaisePropertyChanged("ZHUANLIZQX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string HETONGZT {
            get {
                return this.hETONGZTField;
            }
            set {
                this.hETONGZTField = value;
                this.RaisePropertyChanged("HETONGZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
                this.RaisePropertyChanged("DENGJISXR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
                this.RaisePropertyChanged("BIANGENGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
                this.RaisePropertyChanged("JIECHUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DENGJIH {
            get {
                return this.dENGJIHField;
            }
            set {
                this.dENGJIHField = value;
                this.RaisePropertyChanged("DENGJIH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CHUZHIR {
            get {
                return this.cHUZHIRField;
            }
            set {
                this.cHUZHIRField = value;
                this.RaisePropertyChanged("CHUZHIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ZHIQUANR {
            get {
                return this.zHIQUANRField;
            }
            set {
                this.zHIQUANRField = value;
                this.RaisePropertyChanged("ZHIQUANR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
                this.RaisePropertyChanged("DETAIL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal012 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string dENGJISXRField;
        
        private string bIANGENGSXField;
        
        private string bIANGENGQQLRField;
        
        private string bIANGENGHQLRField;
        
        private string bIANGENGQDZField;
        
        private string bIANGENGHDZField;
        
        private string dETAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
                this.RaisePropertyChanged("JUANQI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
                this.RaisePropertyChanged("PatentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
                this.RaisePropertyChanged("LegalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
                this.RaisePropertyChanged("LegalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
                this.RaisePropertyChanged("LegalStatusInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
                this.RaisePropertyChanged("LegalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
                this.RaisePropertyChanged("SHENQINGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
                this.RaisePropertyChanged("ZHUANLIMC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
                this.RaisePropertyChanged("IPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
                this.RaisePropertyChanged("ZHUANLIZY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
                this.RaisePropertyChanged("ZHUANLIZQX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
                this.RaisePropertyChanged("DENGJISXR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BIANGENGSX {
            get {
                return this.bIANGENGSXField;
            }
            set {
                this.bIANGENGSXField = value;
                this.RaisePropertyChanged("BIANGENGSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BIANGENGQQLR {
            get {
                return this.bIANGENGQQLRField;
            }
            set {
                this.bIANGENGQQLRField = value;
                this.RaisePropertyChanged("BIANGENGQQLR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BIANGENGHQLR {
            get {
                return this.bIANGENGHQLRField;
            }
            set {
                this.bIANGENGHQLRField = value;
                this.RaisePropertyChanged("BIANGENGHQLR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BIANGENGQDZ {
            get {
                return this.bIANGENGQDZField;
            }
            set {
                this.bIANGENGQDZField = value;
                this.RaisePropertyChanged("BIANGENGQDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BIANGENGHDZ {
            get {
                return this.bIANGENGHDZField;
            }
            set {
                this.bIANGENGHDZField = value;
                this.RaisePropertyChanged("BIANGENGHDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
                this.RaisePropertyChanged("DETAIL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchPattern : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private string searchNoField;
        
        private string patternField;
        
        private SearchDbType dbTypeField;
        
        private string strCnpFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchNo {
            get {
                return this.searchNoField;
            }
            set {
                this.searchNoField = value;
                this.RaisePropertyChanged("SearchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
                this.RaisePropertyChanged("Pattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SearchDbType DbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
                this.RaisePropertyChanged("DbType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StrCnpFile {
            get {
                return this.strCnpFileField;
            }
            set {
                this.strCnpFileField = value;
                this.RaisePropertyChanged("StrCnpFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchDbType {
        
        /// <remarks/>
        Cn,
        
        /// <remarks/>
        DocDB,
        
        /// <remarks/>
        Dwpi,
        
        /// <remarks/>
        UserCustomLibrary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchPattern searchPatternField;
        
        private string hitMsgField;
        
        private int hitCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SearchPattern SearchPattern {
            get {
                return this.searchPatternField;
            }
            set {
                this.searchPatternField = value;
                this.RaisePropertyChanged("SearchPattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HitMsg {
            get {
                return this.hitMsgField;
            }
            set {
                this.hitMsgField = value;
                this.RaisePropertyChanged("HitMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int HitCount {
            get {
                return this.hitCountField;
            }
            set {
                this.hitCountField = value;
                this.RaisePropertyChanged("HitCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SearchInterface.WSFLZT.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SearchInterface.WSFLZT.ServiceSoap>, SearchInterface.WSFLZT.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CnLegalStatus[] GetCnLegal(string sAppno) {
            return base.Channel.GetCnLegal(sAppno);
        }
        
        public CnLegalStatus[] GetCnLegalDetail(string sAppno) {
            return base.Channel.GetCnLegalDetail(sAppno);
        }
        
        public System.Data.DataSet GetCnLegalDetailByAppNo(string sAppno) {
            return base.Channel.GetCnLegalDetailByAppNo(sAppno);
        }
        
        public SearchInterface.WSFLZT.ResultInfo QueryFaLvZT(string AppNo, string GongGaoR, string FaLvZT, string ZhuanLiQR, int UserID) {
            return base.Channel.QueryFaLvZT(AppNo, GongGaoR, FaLvZT, ZhuanLiQR, UserID);
        }
        
        public CnLegalStatus[] QueryFaLvZTGetList(string SearchNo, int PageIndex, int PageSize, int UserID) {
            return base.Channel.QueryFaLvZTGetList(SearchNo, PageIndex, PageSize, UserID);
        }
        
        public CnLegal012[] QueryZhuanYi(out int pagCount, string AppNo, string IPC, string DengJISXR, string BianGengQQLR, string BianGengHQLR, string BianGengQDZ, string BianGengHDZ, int pagIndex, int pagSize) {
            return base.Channel.QueryZhuanYi(out pagCount, AppNo, IPC, DengJISXR, BianGengQQLR, BianGengHQLR, BianGengQDZ, BianGengHDZ, pagIndex, pagSize);
        }
        
        public CnLegal015[] QueryZhiYa(out int pagCount, string AppNo, string IPC, string HeTongZT, string DengJiSXR, string BianGengR, string JieChuR, string DengJiH, string CHuZhiR, string ZhiQuanR, int pagIndex, int pagSize) {
            return base.Channel.QueryZhiYa(out pagCount, AppNo, IPC, HeTongZT, DengJiSXR, BianGengR, JieChuR, DengJiH, CHuZhiR, ZhiQuanR, pagIndex, pagSize);
        }
        
        public CnLegal014[] QueryShiShiXuKe(out int pagCount, string AppNo, string IPC, string XuKeZL, string HeTongZT, string BeiAnRQ, string BianGengR, string JIeChuR, string HeTongBAH, string RangYuR, string SHouRangR, int pagIndex, int pagSize) {
            return base.Channel.QueryShiShiXuKe(out pagCount, AppNo, IPC, XuKeZL, HeTongZT, BeiAnRQ, BianGengR, JIeChuR, HeTongBAH, RangYuR, SHouRangR, pagIndex, pagSize);
        }
        
        public TbCnLegalStatusNew[] QueryFaLvZhuangTai(out int pagCount, string AppNo, string LegalDate, string LegalStatusInfo, string ShenQingRenAppNo, int pagIndex, int pagSize) {
            return base.Channel.QueryFaLvZhuangTai(out pagCount, AppNo, LegalDate, LegalStatusInfo, ShenQingRenAppNo, pagIndex, pagSize);
        }
        
        public string getFaLvZhuangTaiSimple(string AppNo) {
            return base.Channel.getFaLvZhuangTaiSimple(AppNo);
        }
    }
}
