#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpic.Cprs2010.Search.ResultData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataInfo")]
	public partial class ResultDataManagerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertDwpiAccessionNoSerialNo(DwpiAccessionNoSerialNo instance);
    partial void UpdateDwpiAccessionNoSerialNo(DwpiAccessionNoSerialNo instance);
    partial void DeleteDwpiAccessionNoSerialNo(DwpiAccessionNoSerialNo instance);
    partial void InsertDocdbFamilyInfo(DocdbFamilyInfo instance);
    partial void UpdateDocdbFamilyInfo(DocdbFamilyInfo instance);
    partial void DeleteDocdbFamilyInfo(DocdbFamilyInfo instance);
    partial void InsertDocdbDocInfo(DocdbDocInfo instance);
    partial void UpdateDocdbDocInfo(DocdbDocInfo instance);
    partial void DeleteDocdbDocInfo(DocdbDocInfo instance);
    partial void InsertCnGeneral_Info(CnGeneral_Info instance);
    partial void UpdateCnGeneral_Info(CnGeneral_Info instance);
    partial void DeleteCnGeneral_Info(CnGeneral_Info instance);
    #endregion
		
		public ResultDataManagerDataContext() : 
				base(global::Cpic.Cprs2010.Search.ResultData.Properties.Settings.Default.DataInfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ResultDataManagerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResultDataManagerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResultDataManagerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResultDataManagerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DwpiAccessionNoSerialNo> DwpiAccessionNoSerialNo
		{
			get
			{
				return this.GetTable<DwpiAccessionNoSerialNo>();
			}
		}
		
		public System.Data.Linq.Table<DocdbFamilyInfo> DocdbFamilyInfo
		{
			get
			{
				return this.GetTable<DocdbFamilyInfo>();
			}
		}
		
		public System.Data.Linq.Table<DocdbDocInfo> DocdbDocInfo
		{
			get
			{
				return this.GetTable<DocdbDocInfo>();
			}
		}
		
		public System.Data.Linq.Table<CnGeneral_Info> CnGeneral_Info
		{
			get
			{
				return this.GetTable<CnGeneral_Info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DwpiAccessionNoSerialNo")]
	public partial class DwpiAccessionNoSerialNo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _AccessionNo;
		
		private long _SerialNo;
		
		private byte _IndexFlag;
		
		private string _AppNo;
		
		private string _PublicNo;
		
		private string _Title;
		
		private string _IPC;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnAccessionNoChanging(string value);
    partial void OnAccessionNoChanged();
    partial void OnSerialNoChanging(long value);
    partial void OnSerialNoChanged();
    partial void OnIndexFlagChanging(byte value);
    partial void OnIndexFlagChanged();
    partial void OnAppNoChanging(string value);
    partial void OnAppNoChanged();
    partial void OnPublicNoChanging(string value);
    partial void OnPublicNoChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnIPCChanging(string value);
    partial void OnIPCChanged();
    #endregion
		
		public DwpiAccessionNoSerialNo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessionNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AccessionNo
		{
			get
			{
				return this._AccessionNo;
			}
			set
			{
				if ((this._AccessionNo != value))
				{
					this.OnAccessionNoChanging(value);
					this.SendPropertyChanging();
					this._AccessionNo = value;
					this.SendPropertyChanged("AccessionNo");
					this.OnAccessionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="BigInt NOT NULL")]
		public long SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexFlag", DbType="TinyInt NOT NULL")]
		public byte IndexFlag
		{
			get
			{
				return this._IndexFlag;
			}
			set
			{
				if ((this._IndexFlag != value))
				{
					this.OnIndexFlagChanging(value);
					this.SendPropertyChanging();
					this._IndexFlag = value;
					this.SendPropertyChanged("IndexFlag");
					this.OnIndexFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppNo", DbType="VarChar(50)")]
		public string AppNo
		{
			get
			{
				return this._AppNo;
			}
			set
			{
				if ((this._AppNo != value))
				{
					this.OnAppNoChanging(value);
					this.SendPropertyChanging();
					this._AppNo = value;
					this.SendPropertyChanged("AppNo");
					this.OnAppNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicNo", DbType="VarChar(50)")]
		public string PublicNo
		{
			get
			{
				return this._PublicNo;
			}
			set
			{
				if ((this._PublicNo != value))
				{
					this.OnPublicNoChanging(value);
					this.SendPropertyChanging();
					this._PublicNo = value;
					this.SendPropertyChanged("PublicNo");
					this.OnPublicNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPC", DbType="VarChar(80)")]
		public string IPC
		{
			get
			{
				return this._IPC;
			}
			set
			{
				if ((this._IPC != value))
				{
					this.OnIPCChanging(value);
					this.SendPropertyChanging();
					this._IPC = value;
					this.SendPropertyChanged("IPC");
					this.OnIPCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocdbFamilyInfo")]
	public partial class DocdbFamilyInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CPIC;
		
		private string _PubIDs;
		
		private int _IndexFlag;
		
		private string _Title;
		
		private string _IPC;
		
		private string _AppNo;
		
		private string _AppDate;
		
		private string _OldPubIDs;
		
		private System.Nullable<int> _isChanged;
		
		private System.Nullable<int> _PreIndexFlag;
		
		private System.Nullable<int> _PubIDNum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPICChanging(int value);
    partial void OnCPICChanged();
    partial void OnPubIDsChanging(string value);
    partial void OnPubIDsChanged();
    partial void OnIndexFlagChanging(int value);
    partial void OnIndexFlagChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnIPCChanging(string value);
    partial void OnIPCChanged();
    partial void OnAppNoChanging(string value);
    partial void OnAppNoChanged();
    partial void OnAppDateChanging(string value);
    partial void OnAppDateChanged();
    partial void OnOldPubIDsChanging(string value);
    partial void OnOldPubIDsChanged();
    partial void OnisChangedChanging(System.Nullable<int> value);
    partial void OnisChangedChanged();
    partial void OnPreIndexFlagChanging(System.Nullable<int> value);
    partial void OnPreIndexFlagChanged();
    partial void OnPubIDNumChanging(System.Nullable<int> value);
    partial void OnPubIDNumChanged();
    #endregion
		
		public DocdbFamilyInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPIC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CPIC
		{
			get
			{
				return this._CPIC;
			}
			set
			{
				if ((this._CPIC != value))
				{
					this.OnCPICChanging(value);
					this.SendPropertyChanging();
					this._CPIC = value;
					this.SendPropertyChanged("CPIC");
					this.OnCPICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PubIDs", DbType="NVarChar(MAX)")]
		public string PubIDs
		{
			get
			{
				return this._PubIDs;
			}
			set
			{
				if ((this._PubIDs != value))
				{
					this.OnPubIDsChanging(value);
					this.SendPropertyChanging();
					this._PubIDs = value;
					this.SendPropertyChanged("PubIDs");
					this.OnPubIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexFlag", DbType="Int NOT NULL")]
		public int IndexFlag
		{
			get
			{
				return this._IndexFlag;
			}
			set
			{
				if ((this._IndexFlag != value))
				{
					this.OnIndexFlagChanging(value);
					this.SendPropertyChanging();
					this._IndexFlag = value;
					this.SendPropertyChanged("IndexFlag");
					this.OnIndexFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPC", DbType="VarChar(80)")]
		public string IPC
		{
			get
			{
				return this._IPC;
			}
			set
			{
				if ((this._IPC != value))
				{
					this.OnIPCChanging(value);
					this.SendPropertyChanging();
					this._IPC = value;
					this.SendPropertyChanged("IPC");
					this.OnIPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppNo", DbType="VarChar(20)")]
		public string AppNo
		{
			get
			{
				return this._AppNo;
			}
			set
			{
				if ((this._AppNo != value))
				{
					this.OnAppNoChanging(value);
					this.SendPropertyChanging();
					this._AppNo = value;
					this.SendPropertyChanged("AppNo");
					this.OnAppNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDate", DbType="VarChar(10)")]
		public string AppDate
		{
			get
			{
				return this._AppDate;
			}
			set
			{
				if ((this._AppDate != value))
				{
					this.OnAppDateChanging(value);
					this.SendPropertyChanging();
					this._AppDate = value;
					this.SendPropertyChanged("AppDate");
					this.OnAppDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldPubIDs", DbType="NVarChar(MAX)")]
		public string OldPubIDs
		{
			get
			{
				return this._OldPubIDs;
			}
			set
			{
				if ((this._OldPubIDs != value))
				{
					this.OnOldPubIDsChanging(value);
					this.SendPropertyChanging();
					this._OldPubIDs = value;
					this.SendPropertyChanged("OldPubIDs");
					this.OnOldPubIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isChanged", DbType="Int")]
		public System.Nullable<int> isChanged
		{
			get
			{
				return this._isChanged;
			}
			set
			{
				if ((this._isChanged != value))
				{
					this.OnisChangedChanging(value);
					this.SendPropertyChanging();
					this._isChanged = value;
					this.SendPropertyChanged("isChanged");
					this.OnisChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreIndexFlag", DbType="Int")]
		public System.Nullable<int> PreIndexFlag
		{
			get
			{
				return this._PreIndexFlag;
			}
			set
			{
				if ((this._PreIndexFlag != value))
				{
					this.OnPreIndexFlagChanging(value);
					this.SendPropertyChanging();
					this._PreIndexFlag = value;
					this.SendPropertyChanged("PreIndexFlag");
					this.OnPreIndexFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PubIDNum", DbType="Int")]
		public System.Nullable<int> PubIDNum
		{
			get
			{
				return this._PubIDNum;
			}
			set
			{
				if ((this._PubIDNum != value))
				{
					this.OnPubIDNumChanging(value);
					this.SendPropertyChanging();
					this._PubIDNum = value;
					this.SendPropertyChanged("PubIDNum");
					this.OnPubIDNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocdbDocInfo")]
	public partial class DocdbDocInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PubID;
		
		private System.Nullable<int> _CPIC;
		
		private string _Title;
		
		private string _IPC;
		
		private string _AppNo;
		
		private string _AppDate;
		
		private System.Nullable<int> _IndexFlag;
		
		private string _PR;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPubIDChanging(string value);
    partial void OnPubIDChanged();
    partial void OnCPICChanging(System.Nullable<int> value);
    partial void OnCPICChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnIPCChanging(string value);
    partial void OnIPCChanged();
    partial void OnAppNoChanging(string value);
    partial void OnAppNoChanged();
    partial void OnAppDateChanging(string value);
    partial void OnAppDateChanged();
    partial void OnIndexFlagChanging(System.Nullable<int> value);
    partial void OnIndexFlagChanged();
    partial void OnPRChanging(string value);
    partial void OnPRChanged();
    #endregion
		
		public DocdbDocInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PubID", DbType="NVarChar(20)")]
		public string PubID
		{
			get
			{
				return this._PubID;
			}
			set
			{
				if ((this._PubID != value))
				{
					this.OnPubIDChanging(value);
					this.SendPropertyChanging();
					this._PubID = value;
					this.SendPropertyChanged("PubID");
					this.OnPubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPIC", DbType="Int")]
		public System.Nullable<int> CPIC
		{
			get
			{
				return this._CPIC;
			}
			set
			{
				if ((this._CPIC != value))
				{
					this.OnCPICChanging(value);
					this.SendPropertyChanging();
					this._CPIC = value;
					this.SendPropertyChanged("CPIC");
					this.OnCPICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPC", DbType="VarChar(80)")]
		public string IPC
		{
			get
			{
				return this._IPC;
			}
			set
			{
				if ((this._IPC != value))
				{
					this.OnIPCChanging(value);
					this.SendPropertyChanging();
					this._IPC = value;
					this.SendPropertyChanged("IPC");
					this.OnIPCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppNo", DbType="VarChar(20)")]
		public string AppNo
		{
			get
			{
				return this._AppNo;
			}
			set
			{
				if ((this._AppNo != value))
				{
					this.OnAppNoChanging(value);
					this.SendPropertyChanging();
					this._AppNo = value;
					this.SendPropertyChanged("AppNo");
					this.OnAppNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDate", DbType="VarChar(10)")]
		public string AppDate
		{
			get
			{
				return this._AppDate;
			}
			set
			{
				if ((this._AppDate != value))
				{
					this.OnAppDateChanging(value);
					this.SendPropertyChanging();
					this._AppDate = value;
					this.SendPropertyChanged("AppDate");
					this.OnAppDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexFlag", DbType="Int")]
		public System.Nullable<int> IndexFlag
		{
			get
			{
				return this._IndexFlag;
			}
			set
			{
				if ((this._IndexFlag != value))
				{
					this.OnIndexFlagChanging(value);
					this.SendPropertyChanging();
					this._IndexFlag = value;
					this.SendPropertyChanged("IndexFlag");
					this.OnIndexFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR", DbType="VarChar(MAX)")]
		public string PR
		{
			get
			{
				return this._PR;
			}
			set
			{
				if ((this._PR != value))
				{
					this.OnPRChanging(value);
					this.SendPropertyChanging();
					this._PR = value;
					this.SendPropertyChanged("PR");
					this.OnPRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CnGeneral_Info")]
	public partial class CnGeneral_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SerialNo;
		
		private string _ApNo;
		
		private string _ApDate;
		
		private string _Ipc1;
		
		private string _Title;
		
		private byte _DelFlag;
		
		private string _titleen;
		
		private string _ApNo12;
		
		private System.Nullable<int> _zlnl;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialNoChanging(long value);
    partial void OnSerialNoChanged();
    partial void OnApNoChanging(string value);
    partial void OnApNoChanged();
    partial void OnApDateChanging(string value);
    partial void OnApDateChanged();
    partial void OnIpc1Changing(string value);
    partial void OnIpc1Changed();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDelFlagChanging(byte value);
    partial void OnDelFlagChanged();
    partial void OntitleenChanging(string value);
    partial void OntitleenChanged();
    partial void OnApNo12Changing(string value);
    partial void OnApNo12Changed();
    partial void OnzlnlChanging(System.Nullable<int> value);
    partial void OnzlnlChanged();
    #endregion
		
		public CnGeneral_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApNo", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string ApNo
		{
			get
			{
				return this._ApNo;
			}
			set
			{
				if ((this._ApNo != value))
				{
					this.OnApNoChanging(value);
					this.SendPropertyChanging();
					this._ApNo = value;
					this.SendPropertyChanged("ApNo");
					this.OnApNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApDate", DbType="VarChar(20)")]
		public string ApDate
		{
			get
			{
				return this._ApDate;
			}
			set
			{
				if ((this._ApDate != value))
				{
					this.OnApDateChanging(value);
					this.SendPropertyChanging();
					this._ApDate = value;
					this.SendPropertyChanged("ApDate");
					this.OnApDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ipc1", DbType="VarChar(14)")]
		public string Ipc1
		{
			get
			{
				return this._Ipc1;
			}
			set
			{
				if ((this._Ipc1 != value))
				{
					this.OnIpc1Changing(value);
					this.SendPropertyChanging();
					this._Ipc1 = value;
					this.SendPropertyChanged("Ipc1");
					this.OnIpc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(300)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelFlag", DbType="TinyInt NOT NULL")]
		public byte DelFlag
		{
			get
			{
				return this._DelFlag;
			}
			set
			{
				if ((this._DelFlag != value))
				{
					this.OnDelFlagChanging(value);
					this.SendPropertyChanging();
					this._DelFlag = value;
					this.SendPropertyChanged("DelFlag");
					this.OnDelFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titleen", DbType="Char(350)")]
		public string titleen
		{
			get
			{
				return this._titleen;
			}
			set
			{
				if ((this._titleen != value))
				{
					this.OntitleenChanging(value);
					this.SendPropertyChanging();
					this._titleen = value;
					this.SendPropertyChanged("titleen");
					this.OntitleenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApNo12", DbType="VarChar(12)")]
		public string ApNo12
		{
			get
			{
				return this._ApNo12;
			}
			set
			{
				if ((this._ApNo12 != value))
				{
					this.OnApNo12Changing(value);
					this.SendPropertyChanging();
					this._ApNo12 = value;
					this.SendPropertyChanged("ApNo12");
					this.OnApNo12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zlnl", DbType="Int")]
		public System.Nullable<int> zlnl
		{
			get
			{
				return this._zlnl;
			}
			set
			{
				if ((this._zlnl != value))
				{
					this.OnzlnlChanging(value);
					this.SendPropertyChanging();
					this._zlnl = value;
					this.SendPropertyChanged("zlnl");
					this.OnzlnlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
