bcp PatentQuery_TG.dbo.tbuser  out c:\out\tbuser.txt  -U"sa" -P"sa@123456" -c -t"|"
bcp PatentQuery_TG.dbo.TbRight  out c:\out\TbRight.txt  -U"sa" -P"sa@123456" -c -t"|"
bcp PatentQuery_TG.dbo.TbRole  out c:\out\TbRole.txt  -U"sa" -P"sa@123456" -c -t"|"
bcp PatentQuery_TG.dbo.TbRoleRight  out c:\out\TbRoleRight.txt  -U"sa" -P"sa@123456" -c -t"|"
bcp PatentQuery_TG.dbo.TbUserRole  out c:\out\TbUserRole.txt  -U"sa" -P"sa@123456" -c -t"|"
bcp PatentQuery_TG.dbo.TLC_Collects  out c:\out\TLC_Collects.txt  -U"sa" -P"sa@123456" -c -t"|"