//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpic.Cprs2010.Cfg.TranslationC2EService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslationC2EService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strContent 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServiceC2E", ReplyAction="*")]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2EResponse WebServiceC2E(Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strCnApNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSC2EByApNo", ReplyAction="*")]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoResponse WSC2EByApNo(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strCnApNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSC2EByApNoExtend", ReplyAction="*")]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendResponse WSC2EByApNoExtend(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceC2ERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceC2E", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequestBody Body;
        
        public WebServiceC2ERequest() {
        }
        
        public WebServiceC2ERequest(Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceC2ERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strContent;
        
        public WebServiceC2ERequestBody() {
        }
        
        public WebServiceC2ERequestBody(string strContent) {
            this.strContent = strContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceC2EResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceC2EResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2EResponseBody Body;
        
        public WebServiceC2EResponse() {
        }
        
        public WebServiceC2EResponse(Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2EResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceC2EResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebServiceC2EResult;
        
        public WebServiceC2EResponseBody() {
        }
        
        public WebServiceC2EResponseBody(string WebServiceC2EResult) {
            this.WebServiceC2EResult = WebServiceC2EResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSC2EByApNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSC2EByApNo", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequestBody Body;
        
        public WSC2EByApNoRequest() {
        }
        
        public WSC2EByApNoRequest(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSC2EByApNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCnApNo;
        
        public WSC2EByApNoRequestBody() {
        }
        
        public WSC2EByApNoRequestBody(string strCnApNo) {
            this.strCnApNo = strCnApNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSC2EByApNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSC2EByApNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoResponseBody Body;
        
        public WSC2EByApNoResponse() {
        }
        
        public WSC2EByApNoResponse(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSC2EByApNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WSC2EByApNoResult;
        
        public WSC2EByApNoResponseBody() {
        }
        
        public WSC2EByApNoResponseBody(string WSC2EByApNoResult) {
            this.WSC2EByApNoResult = WSC2EByApNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSC2EByApNoExtendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSC2EByApNoExtend", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequestBody Body;
        
        public WSC2EByApNoExtendRequest() {
        }
        
        public WSC2EByApNoExtendRequest(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSC2EByApNoExtendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCnApNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strBodyType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nTrsStartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int nTrsEndNo;
        
        public WSC2EByApNoExtendRequestBody() {
        }
        
        public WSC2EByApNoExtendRequestBody(string strCnApNo, string strBodyType, int nTrsStartNo, int nTrsEndNo) {
            this.strCnApNo = strCnApNo;
            this.strBodyType = strBodyType;
            this.nTrsStartNo = nTrsStartNo;
            this.nTrsEndNo = nTrsEndNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSC2EByApNoExtendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSC2EByApNoExtendResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendResponseBody Body;
        
        public WSC2EByApNoExtendResponse() {
        }
        
        public WSC2EByApNoExtendResponse(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSC2EByApNoExtendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WSC2EByApNoExtendResult;
        
        public WSC2EByApNoExtendResponseBody() {
        }
        
        public WSC2EByApNoExtendResponseBody(string WSC2EByApNoExtendResult) {
            this.WSC2EByApNoExtendResult = WSC2EByApNoExtendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap>, Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2EResponse Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap.WebServiceC2E(Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequest request) {
            return base.Channel.WebServiceC2E(request);
        }
        
        public string WebServiceC2E(string strContent) {
            Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequest inValue = new Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequest();
            inValue.Body = new Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2ERequestBody();
            inValue.Body.strContent = strContent;
            Cpic.Cprs2010.Cfg.TranslationC2EService.WebServiceC2EResponse retVal = ((Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap)(this)).WebServiceC2E(inValue);
            return retVal.Body.WebServiceC2EResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoResponse Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap.WSC2EByApNo(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequest request) {
            return base.Channel.WSC2EByApNo(request);
        }
        
        public string WSC2EByApNo(string strCnApNo) {
            Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequest inValue = new Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequest();
            inValue.Body = new Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoRequestBody();
            inValue.Body.strCnApNo = strCnApNo;
            Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoResponse retVal = ((Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap)(this)).WSC2EByApNo(inValue);
            return retVal.Body.WSC2EByApNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendResponse Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap.WSC2EByApNoExtend(Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequest request) {
            return base.Channel.WSC2EByApNoExtend(request);
        }
        
        public string WSC2EByApNoExtend(string strCnApNo, string strBodyType, int nTrsStartNo, int nTrsEndNo) {
            Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequest inValue = new Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequest();
            inValue.Body = new Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendRequestBody();
            inValue.Body.strCnApNo = strCnApNo;
            inValue.Body.strBodyType = strBodyType;
            inValue.Body.nTrsStartNo = nTrsStartNo;
            inValue.Body.nTrsEndNo = nTrsEndNo;
            Cpic.Cprs2010.Cfg.TranslationC2EService.WSC2EByApNoExtendResponse retVal = ((Cpic.Cprs2010.Cfg.TranslationC2EService.ServiceSoap)(this)).WSC2EByApNoExtend(inValue);
            return retVal.Body.WSC2EByApNoExtendResult;
        }
    }
}
