//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchInterface.BiaoYin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiaoYin.WebSerIndexingSoap")]
    public interface WebSerIndexingSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SearchInterface.BiaoYin.HelloWorldResponse HelloWorld(SearchInterface.BiaoYin.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strApNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAutoIndexWord", ReplyAction="*")]
        SearchInterface.BiaoYin.getAutoIndexWordResponse getAutoIndexWord(SearchInterface.BiaoYin.getAutoIndexWordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.BiaoYin.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SearchInterface.BiaoYin.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.BiaoYin.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SearchInterface.BiaoYin.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoIndexWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoIndexWord", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.BiaoYin.getAutoIndexWordRequestBody Body;
        
        public getAutoIndexWordRequest() {
        }
        
        public getAutoIndexWordRequest(SearchInterface.BiaoYin.getAutoIndexWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoIndexWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strApNo;
        
        public getAutoIndexWordRequestBody() {
        }
        
        public getAutoIndexWordRequestBody(string strApNo) {
            this.strApNo = strApNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoIndexWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoIndexWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.BiaoYin.getAutoIndexWordResponseBody Body;
        
        public getAutoIndexWordResponse() {
        }
        
        public getAutoIndexWordResponse(SearchInterface.BiaoYin.getAutoIndexWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoIndexWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SearchInterface.BiaoYin.ArrayOfString getAutoIndexWordResult;
        
        public getAutoIndexWordResponseBody() {
        }
        
        public getAutoIndexWordResponseBody(SearchInterface.BiaoYin.ArrayOfString getAutoIndexWordResult) {
            this.getAutoIndexWordResult = getAutoIndexWordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebSerIndexingSoapChannel : SearchInterface.BiaoYin.WebSerIndexingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSerIndexingSoapClient : System.ServiceModel.ClientBase<SearchInterface.BiaoYin.WebSerIndexingSoap>, SearchInterface.BiaoYin.WebSerIndexingSoap {
        
        public WebSerIndexingSoapClient() {
        }
        
        public WebSerIndexingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSerIndexingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSerIndexingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSerIndexingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.BiaoYin.HelloWorldResponse SearchInterface.BiaoYin.WebSerIndexingSoap.HelloWorld(SearchInterface.BiaoYin.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SearchInterface.BiaoYin.HelloWorldRequest inValue = new SearchInterface.BiaoYin.HelloWorldRequest();
            inValue.Body = new SearchInterface.BiaoYin.HelloWorldRequestBody();
            SearchInterface.BiaoYin.HelloWorldResponse retVal = ((SearchInterface.BiaoYin.WebSerIndexingSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.BiaoYin.getAutoIndexWordResponse SearchInterface.BiaoYin.WebSerIndexingSoap.getAutoIndexWord(SearchInterface.BiaoYin.getAutoIndexWordRequest request) {
            return base.Channel.getAutoIndexWord(request);
        }
        
        public SearchInterface.BiaoYin.ArrayOfString getAutoIndexWord(string strApNo) {
            SearchInterface.BiaoYin.getAutoIndexWordRequest inValue = new SearchInterface.BiaoYin.getAutoIndexWordRequest();
            inValue.Body = new SearchInterface.BiaoYin.getAutoIndexWordRequestBody();
            inValue.Body.strApNo = strApNo;
            SearchInterface.BiaoYin.getAutoIndexWordResponse retVal = ((SearchInterface.BiaoYin.WebSerIndexingSoap)(this)).getAutoIndexWord(inValue);
            return retVal.Body.getAutoIndexWordResult;
        }
    }
}
