//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatentWarnning.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchDbType", Namespace="http://tempuri.org/")]
    public enum SearchDbType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cn = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocDB = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dwpi = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCustomLibrary = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfoWebService", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultInfoWebService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PatentWarnning.ServiceReference.ResultInfo ResultInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultSearchFilePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PatentWarnning.ServiceReference.ResultInfo ResultInfo {
            get {
                return this.ResultInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultInfoField, value) != true)) {
                    this.ResultInfoField = value;
                    this.RaisePropertyChanged("ResultInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultSearchFilePath {
            get {
                return this.ResultSearchFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSearchFilePathField, value) != true)) {
                    this.ResultSearchFilePathField = value;
                    this.RaisePropertyChanged("ResultSearchFilePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PatentWarnning.ServiceReference.SearchPattern SearchPatternField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HitMsgField;
        
        private int HitCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PatentWarnning.ServiceReference.SearchPattern SearchPattern {
            get {
                return this.SearchPatternField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchPatternField, value) != true)) {
                    this.SearchPatternField = value;
                    this.RaisePropertyChanged("SearchPattern");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HitMsg {
            get {
                return this.HitMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.HitMsgField, value) != true)) {
                    this.HitMsgField = value;
                    this.RaisePropertyChanged("HitMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int HitCount {
            get {
                return this.HitCountField;
            }
            set {
                if ((this.HitCountField.Equals(value) != true)) {
                    this.HitCountField = value;
                    this.RaisePropertyChanged("HitCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPattern", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SearchPattern : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatternField;
        
        private PatentWarnning.ServiceReference.SearchDbType DbTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCnpFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SearchNo {
            get {
                return this.SearchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchNoField, value) != true)) {
                    this.SearchNoField = value;
                    this.RaisePropertyChanged("SearchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pattern {
            get {
                return this.PatternField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternField, value) != true)) {
                    this.PatternField = value;
                    this.RaisePropertyChanged("Pattern");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public PatentWarnning.ServiceReference.SearchDbType DbType {
            get {
                return this.DbTypeField;
            }
            set {
                if ((this.DbTypeField.Equals(value) != true)) {
                    this.DbTypeField = value;
                    this.RaisePropertyChanged("DbType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StrCnpFile {
            get {
                return this.StrCnpFileField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCnpFileField, value) != true)) {
                    this.StrCnpFileField = value;
                    this.RaisePropertyChanged("StrCnpFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.SearchWebServiceSoap")]
    public interface SearchWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        PatentWarnning.ServiceReference.HelloWorldResponse HelloWorld(PatentWarnning.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strPattern 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        PatentWarnning.ServiceReference.SearchResponse Search(PatentWarnning.ServiceReference.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public PatentWarnning.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PatentWarnning.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public PatentWarnning.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PatentWarnning.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public PatentWarnning.ServiceReference.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(PatentWarnning.ServiceReference.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nSNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public PatentWarnning.ServiceReference.SearchDbType _SDbType;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string strPattern, int UserID, int nSNo, PatentWarnning.ServiceReference.SearchDbType _SDbType) {
            this.strPattern = strPattern;
            this.UserID = UserID;
            this.nSNo = nSNo;
            this._SDbType = _SDbType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public PatentWarnning.ServiceReference.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(PatentWarnning.ServiceReference.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PatentWarnning.ServiceReference.ResultInfoWebService SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(PatentWarnning.ServiceReference.ResultInfoWebService SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchWebServiceSoapChannel : PatentWarnning.ServiceReference.SearchWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchWebServiceSoapClient : System.ServiceModel.ClientBase<PatentWarnning.ServiceReference.SearchWebServiceSoap>, PatentWarnning.ServiceReference.SearchWebServiceSoap {
        
        public SearchWebServiceSoapClient() {
        }
        
        public SearchWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PatentWarnning.ServiceReference.HelloWorldResponse PatentWarnning.ServiceReference.SearchWebServiceSoap.HelloWorld(PatentWarnning.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PatentWarnning.ServiceReference.HelloWorldRequest inValue = new PatentWarnning.ServiceReference.HelloWorldRequest();
            inValue.Body = new PatentWarnning.ServiceReference.HelloWorldRequestBody();
            PatentWarnning.ServiceReference.HelloWorldResponse retVal = ((PatentWarnning.ServiceReference.SearchWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PatentWarnning.ServiceReference.SearchResponse PatentWarnning.ServiceReference.SearchWebServiceSoap.Search(PatentWarnning.ServiceReference.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public PatentWarnning.ServiceReference.ResultInfoWebService Search(string strPattern, int UserID, int nSNo, PatentWarnning.ServiceReference.SearchDbType _SDbType) {
            PatentWarnning.ServiceReference.SearchRequest inValue = new PatentWarnning.ServiceReference.SearchRequest();
            inValue.Body = new PatentWarnning.ServiceReference.SearchRequestBody();
            inValue.Body.strPattern = strPattern;
            inValue.Body.UserID = UserID;
            inValue.Body.nSNo = nSNo;
            inValue.Body._SDbType = _SDbType;
            PatentWarnning.ServiceReference.SearchResponse retVal = ((PatentWarnning.ServiceReference.SearchWebServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
    }
}
