//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchInterface.WSYQ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchDbType", Namespace="http://tempuri.org/")]
    public enum SearchDbType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cn = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocDB = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dwpi = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCustomLibrary = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnThematicDB = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralDataInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GeneralDataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long NCPICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrTIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrTrsTIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrIPCField;
        
        private int NMembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrPubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrPtCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long NCPIC {
            get {
                return this.NCPICField;
            }
            set {
                if ((this.NCPICField.Equals(value) != true)) {
                    this.NCPICField = value;
                    this.RaisePropertyChanged("NCPIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrTI {
            get {
                return this.StrTIField;
            }
            set {
                if ((object.ReferenceEquals(this.StrTIField, value) != true)) {
                    this.StrTIField = value;
                    this.RaisePropertyChanged("StrTI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StrTrsTI {
            get {
                return this.StrTrsTIField;
            }
            set {
                if ((object.ReferenceEquals(this.StrTrsTIField, value) != true)) {
                    this.StrTrsTIField = value;
                    this.RaisePropertyChanged("StrTrsTI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrAN {
            get {
                return this.StrANField;
            }
            set {
                if ((object.ReferenceEquals(this.StrANField, value) != true)) {
                    this.StrANField = value;
                    this.RaisePropertyChanged("StrAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StrAD {
            get {
                return this.StrADField;
            }
            set {
                if ((object.ReferenceEquals(this.StrADField, value) != true)) {
                    this.StrADField = value;
                    this.RaisePropertyChanged("StrAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StrIPC {
            get {
                return this.StrIPCField;
            }
            set {
                if ((object.ReferenceEquals(this.StrIPCField, value) != true)) {
                    this.StrIPCField = value;
                    this.RaisePropertyChanged("StrIPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NMembers {
            get {
                return this.NMembersField;
            }
            set {
                if ((this.NMembersField.Equals(value) != true)) {
                    this.NMembersField = value;
                    this.RaisePropertyChanged("NMembers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StrPubID {
            get {
                return this.StrPubIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StrPubIDField, value) != true)) {
                    this.StrPubIDField = value;
                    this.RaisePropertyChanged("StrPubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StrPtCode {
            get {
                return this.StrPtCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StrPtCodeField, value) != true)) {
                    this.StrPtCodeField = value;
                    this.RaisePropertyChanged("StrPtCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatentDataType", Namespace="http://tempuri.org/")]
    public enum PatentDataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnMabXmlTxt = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnDesXmlTxt = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnClmXmlTxt = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnAbsFuTuUrl = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CnWGImgUrls = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnMabXmlTxt = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDFFileUrl = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSYQ.CprsGIISWebSvcSoap")]
    public interface CprsGIISWebSvcSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SearchInterface.WSYQ.HelloWorldResponse HelloWorld(SearchInterface.WSYQ.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 getYKSearchUserIDResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getYKSearchUserID", ReplyAction="*")]
        SearchInterface.WSYQ.getYKSearchUserIDResponse getYKSearchUserID(SearchInterface.WSYQ.getYKSearchUserIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _strULoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MappingUser", ReplyAction="*")]
        SearchInterface.WSYQ.MappingUserResponse MappingUser(SearchInterface.WSYQ.MappingUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _strUID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoSearch", ReplyAction="*")]
        SearchInterface.WSYQ.DoSearchResponse DoSearch(SearchInterface.WSYQ.DoSearchRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _strUID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeneralData", ReplyAction="*")]
        SearchInterface.WSYQ.GetGeneralDataResponse GetGeneralData(SearchInterface.WSYQ.GetGeneralDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _lstNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeneralDataByLstNo", ReplyAction="*")]
        SearchInterface.WSYQ.GetGeneralDataByLstNoResponse GetGeneralDataByLstNo(SearchInterface.WSYQ.GetGeneralDataByLstNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _strUID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFmlMemberData", ReplyAction="*")]
        SearchInterface.WSYQ.GetFmlMemberDataResponse GetFmlMemberData(SearchInterface.WSYQ.GetFmlMemberDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _strPID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPatentData", ReplyAction="*")]
        SearchInterface.WSYQ.GetPatentDataResponse GetPatentData(SearchInterface.WSYQ.GetPatentDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SearchInterface.WSYQ.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SearchInterface.WSYQ.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getYKSearchUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getYKSearchUserID", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.getYKSearchUserIDRequestBody Body;
        
        public getYKSearchUserIDRequest() {
        }
        
        public getYKSearchUserIDRequest(SearchInterface.WSYQ.getYKSearchUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getYKSearchUserIDRequestBody {
        
        public getYKSearchUserIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getYKSearchUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getYKSearchUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.getYKSearchUserIDResponseBody Body;
        
        public getYKSearchUserIDResponse() {
        }
        
        public getYKSearchUserIDResponse(SearchInterface.WSYQ.getYKSearchUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getYKSearchUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getYKSearchUserIDResult;
        
        public getYKSearchUserIDResponseBody() {
        }
        
        public getYKSearchUserIDResponseBody(string getYKSearchUserIDResult) {
            this.getYKSearchUserIDResult = getYKSearchUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MappingUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MappingUser", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.MappingUserRequestBody Body;
        
        public MappingUserRequest() {
        }
        
        public MappingUserRequest(SearchInterface.WSYQ.MappingUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MappingUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _strULoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _strPwd;
        
        public MappingUserRequestBody() {
        }
        
        public MappingUserRequestBody(string _strULoginName, string _strPwd) {
            this._strULoginName = _strULoginName;
            this._strPwd = _strPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MappingUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MappingUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.MappingUserResponseBody Body;
        
        public MappingUserResponse() {
        }
        
        public MappingUserResponse(SearchInterface.WSYQ.MappingUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MappingUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MappingUserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _strUID;
        
        public MappingUserResponseBody() {
        }
        
        public MappingUserResponseBody(bool MappingUserResult, string _strUID) {
            this.MappingUserResult = MappingUserResult;
            this._strUID = _strUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoSearch", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.DoSearchRequestBody Body;
        
        public DoSearchRequest() {
        }
        
        public DoSearchRequest(SearchInterface.WSYQ.DoSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _strUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SearchInterface.WSYQ.SearchDbType _SDbType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _strSID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _strSearchQuery;
        
        public DoSearchRequestBody() {
        }
        
        public DoSearchRequestBody(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, string _strSID, string _strSearchQuery) {
            this._strUID = _strUID;
            this._SDbType = _SDbType;
            this._strSID = _strSID;
            this._strSearchQuery = _strSearchQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoSearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.DoSearchResponseBody Body;
        
        public DoSearchResponse() {
        }
        
        public DoSearchResponse(SearchInterface.WSYQ.DoSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoSearchResult;
        
        public DoSearchResponseBody() {
        }
        
        public DoSearchResponseBody(string DoSearchResult) {
            this.DoSearchResult = DoSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeneralDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralData", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetGeneralDataRequestBody Body;
        
        public GetGeneralDataRequest() {
        }
        
        public GetGeneralDataRequest(SearchInterface.WSYQ.GetGeneralDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeneralDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _strUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SearchInterface.WSYQ.SearchDbType _SDbType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _strSID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int _pageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int _pageSize;
        
        public GetGeneralDataRequestBody() {
        }
        
        public GetGeneralDataRequestBody(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, string _strSID, int _pageNo, int _pageSize) {
            this._strUID = _strUID;
            this._SDbType = _SDbType;
            this._strSID = _strSID;
            this._pageNo = _pageNo;
            this._pageSize = _pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeneralDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetGeneralDataResponseBody Body;
        
        public GetGeneralDataResponse() {
        }
        
        public GetGeneralDataResponse(SearchInterface.WSYQ.GetGeneralDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeneralDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralDataResult;
        
        public GetGeneralDataResponseBody() {
        }
        
        public GetGeneralDataResponseBody(SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralDataResult) {
            this.GetGeneralDataResult = GetGeneralDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeneralDataByLstNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralDataByLstNo", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetGeneralDataByLstNoRequestBody Body;
        
        public GetGeneralDataByLstNoRequest() {
        }
        
        public GetGeneralDataByLstNoRequest(SearchInterface.WSYQ.GetGeneralDataByLstNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeneralDataByLstNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SearchInterface.WSYQ.ArrayOfInt _lstNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SearchInterface.WSYQ.SearchDbType _SDbType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int _pageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int _pageSize;
        
        public GetGeneralDataByLstNoRequestBody() {
        }
        
        public GetGeneralDataByLstNoRequestBody(SearchInterface.WSYQ.ArrayOfInt _lstNo, SearchInterface.WSYQ.SearchDbType _SDbType, int _pageNo, int _pageSize) {
            this._lstNo = _lstNo;
            this._SDbType = _SDbType;
            this._pageNo = _pageNo;
            this._pageSize = _pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeneralDataByLstNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeneralDataByLstNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetGeneralDataByLstNoResponseBody Body;
        
        public GetGeneralDataByLstNoResponse() {
        }
        
        public GetGeneralDataByLstNoResponse(SearchInterface.WSYQ.GetGeneralDataByLstNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeneralDataByLstNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralDataByLstNoResult;
        
        public GetGeneralDataByLstNoResponseBody() {
        }
        
        public GetGeneralDataByLstNoResponseBody(SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralDataByLstNoResult) {
            this.GetGeneralDataByLstNoResult = GetGeneralDataByLstNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFmlMemberDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFmlMemberData", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetFmlMemberDataRequestBody Body;
        
        public GetFmlMemberDataRequest() {
        }
        
        public GetFmlMemberDataRequest(SearchInterface.WSYQ.GetFmlMemberDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFmlMemberDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _strUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SearchInterface.WSYQ.SearchDbType _SDbType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int _nCPIC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int _pageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int _pageSize;
        
        public GetFmlMemberDataRequestBody() {
        }
        
        public GetFmlMemberDataRequestBody(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, int _nCPIC, int _pageNo, int _pageSize) {
            this._strUID = _strUID;
            this._SDbType = _SDbType;
            this._nCPIC = _nCPIC;
            this._pageNo = _pageNo;
            this._pageSize = _pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFmlMemberDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFmlMemberDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetFmlMemberDataResponseBody Body;
        
        public GetFmlMemberDataResponse() {
        }
        
        public GetFmlMemberDataResponse(SearchInterface.WSYQ.GetFmlMemberDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFmlMemberDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SearchInterface.WSYQ.GeneralDataInfo[] GetFmlMemberDataResult;
        
        public GetFmlMemberDataResponseBody() {
        }
        
        public GetFmlMemberDataResponseBody(SearchInterface.WSYQ.GeneralDataInfo[] GetFmlMemberDataResult) {
            this.GetFmlMemberDataResult = GetFmlMemberDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatentData", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetPatentDataRequestBody Body;
        
        public GetPatentDataRequest() {
        }
        
        public GetPatentDataRequest(SearchInterface.WSYQ.GetPatentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPatentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _strPID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SearchInterface.WSYQ.PatentDataType _PdTpe;
        
        public GetPatentDataRequestBody() {
        }
        
        public GetPatentDataRequestBody(string _strPID, SearchInterface.WSYQ.PatentDataType _PdTpe) {
            this._strPID = _strPID;
            this._PdTpe = _PdTpe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatentDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SearchInterface.WSYQ.GetPatentDataResponseBody Body;
        
        public GetPatentDataResponse() {
        }
        
        public GetPatentDataResponse(SearchInterface.WSYQ.GetPatentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPatentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPatentDataResult;
        
        public GetPatentDataResponseBody() {
        }
        
        public GetPatentDataResponseBody(string GetPatentDataResult) {
            this.GetPatentDataResult = GetPatentDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CprsGIISWebSvcSoapChannel : SearchInterface.WSYQ.CprsGIISWebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CprsGIISWebSvcSoapClient : System.ServiceModel.ClientBase<SearchInterface.WSYQ.CprsGIISWebSvcSoap>, SearchInterface.WSYQ.CprsGIISWebSvcSoap {
        
        public CprsGIISWebSvcSoapClient() {
        }
        
        public CprsGIISWebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CprsGIISWebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CprsGIISWebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CprsGIISWebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.HelloWorldResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.HelloWorld(SearchInterface.WSYQ.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SearchInterface.WSYQ.HelloWorldRequest inValue = new SearchInterface.WSYQ.HelloWorldRequest();
            inValue.Body = new SearchInterface.WSYQ.HelloWorldRequestBody();
            SearchInterface.WSYQ.HelloWorldResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.getYKSearchUserIDResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.getYKSearchUserID(SearchInterface.WSYQ.getYKSearchUserIDRequest request) {
            return base.Channel.getYKSearchUserID(request);
        }
        
        public string getYKSearchUserID() {
            SearchInterface.WSYQ.getYKSearchUserIDRequest inValue = new SearchInterface.WSYQ.getYKSearchUserIDRequest();
            inValue.Body = new SearchInterface.WSYQ.getYKSearchUserIDRequestBody();
            SearchInterface.WSYQ.getYKSearchUserIDResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).getYKSearchUserID(inValue);
            return retVal.Body.getYKSearchUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.MappingUserResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.MappingUser(SearchInterface.WSYQ.MappingUserRequest request) {
            return base.Channel.MappingUser(request);
        }
        
        public bool MappingUser(string _strULoginName, string _strPwd, out string _strUID) {
            SearchInterface.WSYQ.MappingUserRequest inValue = new SearchInterface.WSYQ.MappingUserRequest();
            inValue.Body = new SearchInterface.WSYQ.MappingUserRequestBody();
            inValue.Body._strULoginName = _strULoginName;
            inValue.Body._strPwd = _strPwd;
            SearchInterface.WSYQ.MappingUserResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).MappingUser(inValue);
            _strUID = retVal.Body._strUID;
            return retVal.Body.MappingUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.DoSearchResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.DoSearch(SearchInterface.WSYQ.DoSearchRequest request) {
            return base.Channel.DoSearch(request);
        }
        
        public string DoSearch(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, string _strSID, string _strSearchQuery) {
            SearchInterface.WSYQ.DoSearchRequest inValue = new SearchInterface.WSYQ.DoSearchRequest();
            inValue.Body = new SearchInterface.WSYQ.DoSearchRequestBody();
            inValue.Body._strUID = _strUID;
            inValue.Body._SDbType = _SDbType;
            inValue.Body._strSID = _strSID;
            inValue.Body._strSearchQuery = _strSearchQuery;
            SearchInterface.WSYQ.DoSearchResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).DoSearch(inValue);
            return retVal.Body.DoSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.GetGeneralDataResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.GetGeneralData(SearchInterface.WSYQ.GetGeneralDataRequest request) {
            return base.Channel.GetGeneralData(request);
        }
        
        public SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralData(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, string _strSID, int _pageNo, int _pageSize) {
            SearchInterface.WSYQ.GetGeneralDataRequest inValue = new SearchInterface.WSYQ.GetGeneralDataRequest();
            inValue.Body = new SearchInterface.WSYQ.GetGeneralDataRequestBody();
            inValue.Body._strUID = _strUID;
            inValue.Body._SDbType = _SDbType;
            inValue.Body._strSID = _strSID;
            inValue.Body._pageNo = _pageNo;
            inValue.Body._pageSize = _pageSize;
            SearchInterface.WSYQ.GetGeneralDataResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).GetGeneralData(inValue);
            return retVal.Body.GetGeneralDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.GetGeneralDataByLstNoResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.GetGeneralDataByLstNo(SearchInterface.WSYQ.GetGeneralDataByLstNoRequest request) {
            return base.Channel.GetGeneralDataByLstNo(request);
        }
        
        public SearchInterface.WSYQ.GeneralDataInfo[] GetGeneralDataByLstNo(SearchInterface.WSYQ.ArrayOfInt _lstNo, SearchInterface.WSYQ.SearchDbType _SDbType, int _pageNo, int _pageSize) {
            SearchInterface.WSYQ.GetGeneralDataByLstNoRequest inValue = new SearchInterface.WSYQ.GetGeneralDataByLstNoRequest();
            inValue.Body = new SearchInterface.WSYQ.GetGeneralDataByLstNoRequestBody();
            inValue.Body._lstNo = _lstNo;
            inValue.Body._SDbType = _SDbType;
            inValue.Body._pageNo = _pageNo;
            inValue.Body._pageSize = _pageSize;
            SearchInterface.WSYQ.GetGeneralDataByLstNoResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).GetGeneralDataByLstNo(inValue);
            return retVal.Body.GetGeneralDataByLstNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.GetFmlMemberDataResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.GetFmlMemberData(SearchInterface.WSYQ.GetFmlMemberDataRequest request) {
            return base.Channel.GetFmlMemberData(request);
        }
        
        public SearchInterface.WSYQ.GeneralDataInfo[] GetFmlMemberData(string _strUID, SearchInterface.WSYQ.SearchDbType _SDbType, int _nCPIC, int _pageNo, int _pageSize) {
            SearchInterface.WSYQ.GetFmlMemberDataRequest inValue = new SearchInterface.WSYQ.GetFmlMemberDataRequest();
            inValue.Body = new SearchInterface.WSYQ.GetFmlMemberDataRequestBody();
            inValue.Body._strUID = _strUID;
            inValue.Body._SDbType = _SDbType;
            inValue.Body._nCPIC = _nCPIC;
            inValue.Body._pageNo = _pageNo;
            inValue.Body._pageSize = _pageSize;
            SearchInterface.WSYQ.GetFmlMemberDataResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).GetFmlMemberData(inValue);
            return retVal.Body.GetFmlMemberDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchInterface.WSYQ.GetPatentDataResponse SearchInterface.WSYQ.CprsGIISWebSvcSoap.GetPatentData(SearchInterface.WSYQ.GetPatentDataRequest request) {
            return base.Channel.GetPatentData(request);
        }
        
        public string GetPatentData(string _strPID, SearchInterface.WSYQ.PatentDataType _PdTpe) {
            SearchInterface.WSYQ.GetPatentDataRequest inValue = new SearchInterface.WSYQ.GetPatentDataRequest();
            inValue.Body = new SearchInterface.WSYQ.GetPatentDataRequestBody();
            inValue.Body._strPID = _strPID;
            inValue.Body._PdTpe = _PdTpe;
            SearchInterface.WSYQ.GetPatentDataResponse retVal = ((SearchInterface.WSYQ.CprsGIISWebSvcSoap)(this)).GetPatentData(inValue);
            return retVal.Body.GetPatentDataResult;
        }
    }
}
