//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Patentquery.WSFLZT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCnLegalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCnLegalDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCnLegalDetailByAppNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFaLvZTOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFaLvZTGetListOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryZhuanYiOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryZhiYaOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryShiShiXuKeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFaLvZhuangTaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFaLvZhuangTaiSimpleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Patentquery.Properties.Settings.Default.Patentquery_WSFLZT_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCnLegalCompletedEventHandler GetCnLegalCompleted;
        
        /// <remarks/>
        public event GetCnLegalDetailCompletedEventHandler GetCnLegalDetailCompleted;
        
        /// <remarks/>
        public event GetCnLegalDetailByAppNoCompletedEventHandler GetCnLegalDetailByAppNoCompleted;
        
        /// <remarks/>
        public event QueryFaLvZTCompletedEventHandler QueryFaLvZTCompleted;
        
        /// <remarks/>
        public event QueryFaLvZTGetListCompletedEventHandler QueryFaLvZTGetListCompleted;
        
        /// <remarks/>
        public event QueryZhuanYiCompletedEventHandler QueryZhuanYiCompleted;
        
        /// <remarks/>
        public event QueryZhiYaCompletedEventHandler QueryZhiYaCompleted;
        
        /// <remarks/>
        public event QueryShiShiXuKeCompletedEventHandler QueryShiShiXuKeCompleted;
        
        /// <remarks/>
        public event QueryFaLvZhuangTaiCompletedEventHandler QueryFaLvZhuangTaiCompleted;
        
        /// <remarks/>
        public event getFaLvZhuangTaiSimpleCompletedEventHandler getFaLvZhuangTaiSimpleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCnLegal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegalStatus[] GetCnLegal(string sAppno) {
            object[] results = this.Invoke("GetCnLegal", new object[] {
                        sAppno});
            return ((CnLegalStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCnLegalAsync(string sAppno) {
            this.GetCnLegalAsync(sAppno, null);
        }
        
        /// <remarks/>
        public void GetCnLegalAsync(string sAppno, object userState) {
            if ((this.GetCnLegalOperationCompleted == null)) {
                this.GetCnLegalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCnLegalOperationCompleted);
            }
            this.InvokeAsync("GetCnLegal", new object[] {
                        sAppno}, this.GetCnLegalOperationCompleted, userState);
        }
        
        private void OnGetCnLegalOperationCompleted(object arg) {
            if ((this.GetCnLegalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCnLegalCompleted(this, new GetCnLegalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCnLegalDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegalStatus[] GetCnLegalDetail(string sAppno) {
            object[] results = this.Invoke("GetCnLegalDetail", new object[] {
                        sAppno});
            return ((CnLegalStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCnLegalDetailAsync(string sAppno) {
            this.GetCnLegalDetailAsync(sAppno, null);
        }
        
        /// <remarks/>
        public void GetCnLegalDetailAsync(string sAppno, object userState) {
            if ((this.GetCnLegalDetailOperationCompleted == null)) {
                this.GetCnLegalDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCnLegalDetailOperationCompleted);
            }
            this.InvokeAsync("GetCnLegalDetail", new object[] {
                        sAppno}, this.GetCnLegalDetailOperationCompleted, userState);
        }
        
        private void OnGetCnLegalDetailOperationCompleted(object arg) {
            if ((this.GetCnLegalDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCnLegalDetailCompleted(this, new GetCnLegalDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCnLegalDetailByAppNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCnLegalDetailByAppNo(string sAppno) {
            object[] results = this.Invoke("GetCnLegalDetailByAppNo", new object[] {
                        sAppno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCnLegalDetailByAppNoAsync(string sAppno) {
            this.GetCnLegalDetailByAppNoAsync(sAppno, null);
        }
        
        /// <remarks/>
        public void GetCnLegalDetailByAppNoAsync(string sAppno, object userState) {
            if ((this.GetCnLegalDetailByAppNoOperationCompleted == null)) {
                this.GetCnLegalDetailByAppNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCnLegalDetailByAppNoOperationCompleted);
            }
            this.InvokeAsync("GetCnLegalDetailByAppNo", new object[] {
                        sAppno}, this.GetCnLegalDetailByAppNoOperationCompleted, userState);
        }
        
        private void OnGetCnLegalDetailByAppNoOperationCompleted(object arg) {
            if ((this.GetCnLegalDetailByAppNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCnLegalDetailByAppNoCompleted(this, new GetCnLegalDetailByAppNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFaLvZT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultInfo QueryFaLvZT(string AppNo, string GongGaoR, string FaLvZT, string ZhuanLiQR, int UserID) {
            object[] results = this.Invoke("QueryFaLvZT", new object[] {
                        AppNo,
                        GongGaoR,
                        FaLvZT,
                        ZhuanLiQR,
                        UserID});
            return ((ResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void QueryFaLvZTAsync(string AppNo, string GongGaoR, string FaLvZT, string ZhuanLiQR, int UserID) {
            this.QueryFaLvZTAsync(AppNo, GongGaoR, FaLvZT, ZhuanLiQR, UserID, null);
        }
        
        /// <remarks/>
        public void QueryFaLvZTAsync(string AppNo, string GongGaoR, string FaLvZT, string ZhuanLiQR, int UserID, object userState) {
            if ((this.QueryFaLvZTOperationCompleted == null)) {
                this.QueryFaLvZTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFaLvZTOperationCompleted);
            }
            this.InvokeAsync("QueryFaLvZT", new object[] {
                        AppNo,
                        GongGaoR,
                        FaLvZT,
                        ZhuanLiQR,
                        UserID}, this.QueryFaLvZTOperationCompleted, userState);
        }
        
        private void OnQueryFaLvZTOperationCompleted(object arg) {
            if ((this.QueryFaLvZTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFaLvZTCompleted(this, new QueryFaLvZTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFaLvZTGetList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegalStatus[] QueryFaLvZTGetList(string SearchNo, int PageIndex, int PageSize, int UserID) {
            object[] results = this.Invoke("QueryFaLvZTGetList", new object[] {
                        SearchNo,
                        PageIndex,
                        PageSize,
                        UserID});
            return ((CnLegalStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryFaLvZTGetListAsync(string SearchNo, int PageIndex, int PageSize, int UserID) {
            this.QueryFaLvZTGetListAsync(SearchNo, PageIndex, PageSize, UserID, null);
        }
        
        /// <remarks/>
        public void QueryFaLvZTGetListAsync(string SearchNo, int PageIndex, int PageSize, int UserID, object userState) {
            if ((this.QueryFaLvZTGetListOperationCompleted == null)) {
                this.QueryFaLvZTGetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFaLvZTGetListOperationCompleted);
            }
            this.InvokeAsync("QueryFaLvZTGetList", new object[] {
                        SearchNo,
                        PageIndex,
                        PageSize,
                        UserID}, this.QueryFaLvZTGetListOperationCompleted, userState);
        }
        
        private void OnQueryFaLvZTGetListOperationCompleted(object arg) {
            if ((this.QueryFaLvZTGetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFaLvZTGetListCompleted(this, new QueryFaLvZTGetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryZhuanYi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegal012[] QueryZhuanYi(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string DengJISXR, string BianGengQQLR, string BianGengHQLR, string BianGengQDZ, string BianGengHDZ, int pagIndex, int pagSize, out int pagCount) {
            object[] results = this.Invoke("QueryZhuanYi", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        DengJISXR,
                        BianGengQQLR,
                        BianGengHQLR,
                        BianGengQDZ,
                        BianGengHDZ,
                        pagIndex,
                        pagSize});
            pagCount = ((int)(results[1]));
            return ((CnLegal012[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryZhuanYiAsync(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string DengJISXR, string BianGengQQLR, string BianGengHQLR, string BianGengQDZ, string BianGengHDZ, int pagIndex, int pagSize) {
            this.QueryZhuanYiAsync(AppNo, IPC, ZhuanLiMC, ZhuanLiZY, ZhuanLiZQX, DengJISXR, BianGengQQLR, BianGengHQLR, BianGengQDZ, BianGengHDZ, pagIndex, pagSize, null);
        }
        
        /// <remarks/>
        public void QueryZhuanYiAsync(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string DengJISXR, string BianGengQQLR, string BianGengHQLR, string BianGengQDZ, string BianGengHDZ, int pagIndex, int pagSize, object userState) {
            if ((this.QueryZhuanYiOperationCompleted == null)) {
                this.QueryZhuanYiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryZhuanYiOperationCompleted);
            }
            this.InvokeAsync("QueryZhuanYi", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        DengJISXR,
                        BianGengQQLR,
                        BianGengHQLR,
                        BianGengQDZ,
                        BianGengHDZ,
                        pagIndex,
                        pagSize}, this.QueryZhuanYiOperationCompleted, userState);
        }
        
        private void OnQueryZhuanYiOperationCompleted(object arg) {
            if ((this.QueryZhuanYiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryZhuanYiCompleted(this, new QueryZhuanYiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryZhiYa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegal015[] QueryZhiYa(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string HeTongZT, string DengJiSXR, string BianGengR, string JieChuR, string DengJiH, string CHuZhiR, string ZhiQuanR, int pagIndex, int pagSize, out int pagCount) {
            object[] results = this.Invoke("QueryZhiYa", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        HeTongZT,
                        DengJiSXR,
                        BianGengR,
                        JieChuR,
                        DengJiH,
                        CHuZhiR,
                        ZhiQuanR,
                        pagIndex,
                        pagSize});
            pagCount = ((int)(results[1]));
            return ((CnLegal015[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryZhiYaAsync(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string HeTongZT, string DengJiSXR, string BianGengR, string JieChuR, string DengJiH, string CHuZhiR, string ZhiQuanR, int pagIndex, int pagSize) {
            this.QueryZhiYaAsync(AppNo, IPC, ZhuanLiMC, ZhuanLiZY, ZhuanLiZQX, HeTongZT, DengJiSXR, BianGengR, JieChuR, DengJiH, CHuZhiR, ZhiQuanR, pagIndex, pagSize, null);
        }
        
        /// <remarks/>
        public void QueryZhiYaAsync(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string HeTongZT, string DengJiSXR, string BianGengR, string JieChuR, string DengJiH, string CHuZhiR, string ZhiQuanR, int pagIndex, int pagSize, object userState) {
            if ((this.QueryZhiYaOperationCompleted == null)) {
                this.QueryZhiYaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryZhiYaOperationCompleted);
            }
            this.InvokeAsync("QueryZhiYa", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        HeTongZT,
                        DengJiSXR,
                        BianGengR,
                        JieChuR,
                        DengJiH,
                        CHuZhiR,
                        ZhiQuanR,
                        pagIndex,
                        pagSize}, this.QueryZhiYaOperationCompleted, userState);
        }
        
        private void OnQueryZhiYaOperationCompleted(object arg) {
            if ((this.QueryZhiYaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryZhiYaCompleted(this, new QueryZhiYaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryShiShiXuKe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CnLegal014[] QueryShiShiXuKe(
                    string AppNo, 
                    string IPC, 
                    string ZhuanLiMC, 
                    string ZhuanLiZY, 
                    string ZhuanLiZQX, 
                    string XuKeZL, 
                    string HeTongZT, 
                    string BeiAnRQ, 
                    string BianGengR, 
                    string JIeChuR, 
                    string HeTongBAH, 
                    string RangYuR, 
                    string SHouRangR, 
                    int pagIndex, 
                    int pagSize, 
                    out int pagCount) {
            object[] results = this.Invoke("QueryShiShiXuKe", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        XuKeZL,
                        HeTongZT,
                        BeiAnRQ,
                        BianGengR,
                        JIeChuR,
                        HeTongBAH,
                        RangYuR,
                        SHouRangR,
                        pagIndex,
                        pagSize});
            pagCount = ((int)(results[1]));
            return ((CnLegal014[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryShiShiXuKeAsync(string AppNo, string IPC, string ZhuanLiMC, string ZhuanLiZY, string ZhuanLiZQX, string XuKeZL, string HeTongZT, string BeiAnRQ, string BianGengR, string JIeChuR, string HeTongBAH, string RangYuR, string SHouRangR, int pagIndex, int pagSize) {
            this.QueryShiShiXuKeAsync(AppNo, IPC, ZhuanLiMC, ZhuanLiZY, ZhuanLiZQX, XuKeZL, HeTongZT, BeiAnRQ, BianGengR, JIeChuR, HeTongBAH, RangYuR, SHouRangR, pagIndex, pagSize, null);
        }
        
        /// <remarks/>
        public void QueryShiShiXuKeAsync(
                    string AppNo, 
                    string IPC, 
                    string ZhuanLiMC, 
                    string ZhuanLiZY, 
                    string ZhuanLiZQX, 
                    string XuKeZL, 
                    string HeTongZT, 
                    string BeiAnRQ, 
                    string BianGengR, 
                    string JIeChuR, 
                    string HeTongBAH, 
                    string RangYuR, 
                    string SHouRangR, 
                    int pagIndex, 
                    int pagSize, 
                    object userState) {
            if ((this.QueryShiShiXuKeOperationCompleted == null)) {
                this.QueryShiShiXuKeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryShiShiXuKeOperationCompleted);
            }
            this.InvokeAsync("QueryShiShiXuKe", new object[] {
                        AppNo,
                        IPC,
                        ZhuanLiMC,
                        ZhuanLiZY,
                        ZhuanLiZQX,
                        XuKeZL,
                        HeTongZT,
                        BeiAnRQ,
                        BianGengR,
                        JIeChuR,
                        HeTongBAH,
                        RangYuR,
                        SHouRangR,
                        pagIndex,
                        pagSize}, this.QueryShiShiXuKeOperationCompleted, userState);
        }
        
        private void OnQueryShiShiXuKeOperationCompleted(object arg) {
            if ((this.QueryShiShiXuKeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryShiShiXuKeCompleted(this, new QueryShiShiXuKeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFaLvZhuangTai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TbCnLegalStatusNew[] QueryFaLvZhuangTai(string AppNo, string LegalDate, string LegalStatusInfo, string ShenQingRenAppNo, int pagIndex, int pagSize, out int pagCount) {
            object[] results = this.Invoke("QueryFaLvZhuangTai", new object[] {
                        AppNo,
                        LegalDate,
                        LegalStatusInfo,
                        ShenQingRenAppNo,
                        pagIndex,
                        pagSize});
            pagCount = ((int)(results[1]));
            return ((TbCnLegalStatusNew[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryFaLvZhuangTaiAsync(string AppNo, string LegalDate, string LegalStatusInfo, string ShenQingRenAppNo, int pagIndex, int pagSize) {
            this.QueryFaLvZhuangTaiAsync(AppNo, LegalDate, LegalStatusInfo, ShenQingRenAppNo, pagIndex, pagSize, null);
        }
        
        /// <remarks/>
        public void QueryFaLvZhuangTaiAsync(string AppNo, string LegalDate, string LegalStatusInfo, string ShenQingRenAppNo, int pagIndex, int pagSize, object userState) {
            if ((this.QueryFaLvZhuangTaiOperationCompleted == null)) {
                this.QueryFaLvZhuangTaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFaLvZhuangTaiOperationCompleted);
            }
            this.InvokeAsync("QueryFaLvZhuangTai", new object[] {
                        AppNo,
                        LegalDate,
                        LegalStatusInfo,
                        ShenQingRenAppNo,
                        pagIndex,
                        pagSize}, this.QueryFaLvZhuangTaiOperationCompleted, userState);
        }
        
        private void OnQueryFaLvZhuangTaiOperationCompleted(object arg) {
            if ((this.QueryFaLvZhuangTaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFaLvZhuangTaiCompleted(this, new QueryFaLvZhuangTaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFaLvZhuangTaiSimple", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getFaLvZhuangTaiSimple(string AppNo) {
            object[] results = this.Invoke("getFaLvZhuangTaiSimple", new object[] {
                        AppNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFaLvZhuangTaiSimpleAsync(string AppNo) {
            this.getFaLvZhuangTaiSimpleAsync(AppNo, null);
        }
        
        /// <remarks/>
        public void getFaLvZhuangTaiSimpleAsync(string AppNo, object userState) {
            if ((this.getFaLvZhuangTaiSimpleOperationCompleted == null)) {
                this.getFaLvZhuangTaiSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFaLvZhuangTaiSimpleOperationCompleted);
            }
            this.InvokeAsync("getFaLvZhuangTaiSimple", new object[] {
                        AppNo}, this.getFaLvZhuangTaiSimpleOperationCompleted, userState);
        }
        
        private void OngetFaLvZhuangTaiSimpleOperationCompleted(object arg) {
            if ((this.getFaLvZhuangTaiSimpleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFaLvZhuangTaiSimpleCompleted(this, new getFaLvZhuangTaiSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegalStatus {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string vOLField;
        
        private string nUMField;
        
        private string pAGField;
        
        private string iPCField;
        
        private string sHENQINGHField;
        
        private string sHENQINGRField;
        
        private string sHENQINGGBRField;
        
        private string sHOUQUANGGRField;
        
        private string wUXIAOXGJDHField;
        
        private string wUXIAOXGJDRField;
        
        private string zHONGZHIRField;
        
        private string fANGQISXRField;
        
        private string yUANMINGCField;
        
        private string yUANGONGGRField;
        
        private string bIANGENGSXCODEField;
        
        private string bIANGENGSXField;
        
        private string bIANGENGQField;
        
        private string bIANGENGHField;
        
        private string dENGJISXRField;
        
        private string hETONGBAHField;
        
        private string rANGYURField;
        
        private string sHOURANGRField;
        
        private string zHUANLIMCField;
        
        private string xUKEZLField;
        
        private string bEIANRQField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string dENGJIHField;
        
        private string cHUZHIRField;
        
        private string zHIQUANRField;
        
        private string sHOUJIANRField;
        
        private string wENJIANMCField;
        
        private string sourceFileField;
        
        private System.Nullable<System.DateTime> importDataField;
        
        private string dETAILField;
        
        private string dSHENQINGHField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
            }
        }
        
        /// <remarks/>
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VOL {
            get {
                return this.vOLField;
            }
            set {
                this.vOLField = value;
            }
        }
        
        /// <remarks/>
        public string NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
            }
        }
        
        /// <remarks/>
        public string PAG {
            get {
                return this.pAGField;
            }
            set {
                this.pAGField = value;
            }
        }
        
        /// <remarks/>
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGR {
            get {
                return this.sHENQINGRField;
            }
            set {
                this.sHENQINGRField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGGBR {
            get {
                return this.sHENQINGGBRField;
            }
            set {
                this.sHENQINGGBRField = value;
            }
        }
        
        /// <remarks/>
        public string SHOUQUANGGR {
            get {
                return this.sHOUQUANGGRField;
            }
            set {
                this.sHOUQUANGGRField = value;
            }
        }
        
        /// <remarks/>
        public string WUXIAOXGJDH {
            get {
                return this.wUXIAOXGJDHField;
            }
            set {
                this.wUXIAOXGJDHField = value;
            }
        }
        
        /// <remarks/>
        public string WUXIAOXGJDR {
            get {
                return this.wUXIAOXGJDRField;
            }
            set {
                this.wUXIAOXGJDRField = value;
            }
        }
        
        /// <remarks/>
        public string ZHONGZHIR {
            get {
                return this.zHONGZHIRField;
            }
            set {
                this.zHONGZHIRField = value;
            }
        }
        
        /// <remarks/>
        public string FANGQISXR {
            get {
                return this.fANGQISXRField;
            }
            set {
                this.fANGQISXRField = value;
            }
        }
        
        /// <remarks/>
        public string YUANMINGC {
            get {
                return this.yUANMINGCField;
            }
            set {
                this.yUANMINGCField = value;
            }
        }
        
        /// <remarks/>
        public string YUANGONGGR {
            get {
                return this.yUANGONGGRField;
            }
            set {
                this.yUANGONGGRField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGSXCODE {
            get {
                return this.bIANGENGSXCODEField;
            }
            set {
                this.bIANGENGSXCODEField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGSX {
            get {
                return this.bIANGENGSXField;
            }
            set {
                this.bIANGENGSXField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGQ {
            get {
                return this.bIANGENGQField;
            }
            set {
                this.bIANGENGQField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGH {
            get {
                return this.bIANGENGHField;
            }
            set {
                this.bIANGENGHField = value;
            }
        }
        
        /// <remarks/>
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
            }
        }
        
        /// <remarks/>
        public string HETONGBAH {
            get {
                return this.hETONGBAHField;
            }
            set {
                this.hETONGBAHField = value;
            }
        }
        
        /// <remarks/>
        public string RANGYUR {
            get {
                return this.rANGYURField;
            }
            set {
                this.rANGYURField = value;
            }
        }
        
        /// <remarks/>
        public string SHOURANGR {
            get {
                return this.sHOURANGRField;
            }
            set {
                this.sHOURANGRField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
            }
        }
        
        /// <remarks/>
        public string XUKEZL {
            get {
                return this.xUKEZLField;
            }
            set {
                this.xUKEZLField = value;
            }
        }
        
        /// <remarks/>
        public string BEIANRQ {
            get {
                return this.bEIANRQField;
            }
            set {
                this.bEIANRQField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
            }
        }
        
        /// <remarks/>
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
            }
        }
        
        /// <remarks/>
        public string DENGJIH {
            get {
                return this.dENGJIHField;
            }
            set {
                this.dENGJIHField = value;
            }
        }
        
        /// <remarks/>
        public string CHUZHIR {
            get {
                return this.cHUZHIRField;
            }
            set {
                this.cHUZHIRField = value;
            }
        }
        
        /// <remarks/>
        public string ZHIQUANR {
            get {
                return this.zHIQUANRField;
            }
            set {
                this.zHIQUANRField = value;
            }
        }
        
        /// <remarks/>
        public string SHOUJIANR {
            get {
                return this.sHOUJIANRField;
            }
            set {
                this.sHOUJIANRField = value;
            }
        }
        
        /// <remarks/>
        public string WENJIANMC {
            get {
                return this.wENJIANMCField;
            }
            set {
                this.wENJIANMCField = value;
            }
        }
        
        /// <remarks/>
        public string SourceFile {
            get {
                return this.sourceFileField;
            }
            set {
                this.sourceFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ImportData {
            get {
                return this.importDataField;
            }
            set {
                this.importDataField = value;
            }
        }
        
        /// <remarks/>
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
            }
        }
        
        /// <remarks/>
        public string DSHENQINGH {
            get {
                return this.dSHENQINGHField;
            }
            set {
                this.dSHENQINGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TbCnLegalStatusNew {
        
        private int idField;
        
        private string legalDateField;
        
        private string legalStatusInfoField;
        
        private string detailField;
        
        private string sHENQINGHField;
        
        private string appNoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
            }
        }
        
        /// <remarks/>
        public string AppNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal014 {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string xUKEZLField;
        
        private string hETONGZTField;
        
        private string bEIANRQField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string hETONGBAHField;
        
        private string rANGYURField;
        
        private string sHOURANGRField;
        
        private string dETAILField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
            }
        }
        
        /// <remarks/>
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
            }
        }
        
        /// <remarks/>
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
            }
        }
        
        /// <remarks/>
        public string XUKEZL {
            get {
                return this.xUKEZLField;
            }
            set {
                this.xUKEZLField = value;
            }
        }
        
        /// <remarks/>
        public string HETONGZT {
            get {
                return this.hETONGZTField;
            }
            set {
                this.hETONGZTField = value;
            }
        }
        
        /// <remarks/>
        public string BEIANRQ {
            get {
                return this.bEIANRQField;
            }
            set {
                this.bEIANRQField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
            }
        }
        
        /// <remarks/>
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
            }
        }
        
        /// <remarks/>
        public string HETONGBAH {
            get {
                return this.hETONGBAHField;
            }
            set {
                this.hETONGBAHField = value;
            }
        }
        
        /// <remarks/>
        public string RANGYUR {
            get {
                return this.rANGYURField;
            }
            set {
                this.rANGYURField = value;
            }
        }
        
        /// <remarks/>
        public string SHOURANGR {
            get {
                return this.sHOURANGRField;
            }
            set {
                this.sHOURANGRField = value;
            }
        }
        
        /// <remarks/>
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal015 {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string hETONGZTField;
        
        private string dENGJISXRField;
        
        private string bIANGENGRField;
        
        private string jIECHURField;
        
        private string dENGJIHField;
        
        private string cHUZHIRField;
        
        private string zHIQUANRField;
        
        private string dETAILField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
            }
        }
        
        /// <remarks/>
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
            }
        }
        
        /// <remarks/>
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
            }
        }
        
        /// <remarks/>
        public string HETONGZT {
            get {
                return this.hETONGZTField;
            }
            set {
                this.hETONGZTField = value;
            }
        }
        
        /// <remarks/>
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGR {
            get {
                return this.bIANGENGRField;
            }
            set {
                this.bIANGENGRField = value;
            }
        }
        
        /// <remarks/>
        public string JIECHUR {
            get {
                return this.jIECHURField;
            }
            set {
                this.jIECHURField = value;
            }
        }
        
        /// <remarks/>
        public string DENGJIH {
            get {
                return this.dENGJIHField;
            }
            set {
                this.dENGJIHField = value;
            }
        }
        
        /// <remarks/>
        public string CHUZHIR {
            get {
                return this.cHUZHIRField;
            }
            set {
                this.cHUZHIRField = value;
            }
        }
        
        /// <remarks/>
        public string ZHIQUANR {
            get {
                return this.zHIQUANRField;
            }
            set {
                this.zHIQUANRField = value;
            }
        }
        
        /// <remarks/>
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CnLegal012 {
        
        private long idField;
        
        private string jUANQIField;
        
        private string patentTypeField;
        
        private string legalDateField;
        
        private string legalStatusField;
        
        private string legalStatusInfoField;
        
        private string legalCodeField;
        
        private string sHENQINGHField;
        
        private string zHUANLIMCField;
        
        private string iPCField;
        
        private string zHUANLIZYField;
        
        private string zHUANLIZQXField;
        
        private string dENGJISXRField;
        
        private string bIANGENGSXField;
        
        private string bIANGENGQQLRField;
        
        private string bIANGENGHQLRField;
        
        private string bIANGENGQDZField;
        
        private string bIANGENGHDZField;
        
        private string dETAILField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string JUANQI {
            get {
                return this.jUANQIField;
            }
            set {
                this.jUANQIField = value;
            }
        }
        
        /// <remarks/>
        public string PatentType {
            get {
                return this.patentTypeField;
            }
            set {
                this.patentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatus {
            get {
                return this.legalStatusField;
            }
            set {
                this.legalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LegalStatusInfo {
            get {
                return this.legalStatusInfoField;
            }
            set {
                this.legalStatusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string LegalCode {
            get {
                return this.legalCodeField;
            }
            set {
                this.legalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SHENQINGH {
            get {
                return this.sHENQINGHField;
            }
            set {
                this.sHENQINGHField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIMC {
            get {
                return this.zHUANLIMCField;
            }
            set {
                this.zHUANLIMCField = value;
            }
        }
        
        /// <remarks/>
        public string IPC {
            get {
                return this.iPCField;
            }
            set {
                this.iPCField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZY {
            get {
                return this.zHUANLIZYField;
            }
            set {
                this.zHUANLIZYField = value;
            }
        }
        
        /// <remarks/>
        public string ZHUANLIZQX {
            get {
                return this.zHUANLIZQXField;
            }
            set {
                this.zHUANLIZQXField = value;
            }
        }
        
        /// <remarks/>
        public string DENGJISXR {
            get {
                return this.dENGJISXRField;
            }
            set {
                this.dENGJISXRField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGSX {
            get {
                return this.bIANGENGSXField;
            }
            set {
                this.bIANGENGSXField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGQQLR {
            get {
                return this.bIANGENGQQLRField;
            }
            set {
                this.bIANGENGQQLRField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGHQLR {
            get {
                return this.bIANGENGHQLRField;
            }
            set {
                this.bIANGENGHQLRField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGQDZ {
            get {
                return this.bIANGENGQDZField;
            }
            set {
                this.bIANGENGQDZField = value;
            }
        }
        
        /// <remarks/>
        public string BIANGENGHDZ {
            get {
                return this.bIANGENGHDZField;
            }
            set {
                this.bIANGENGHDZField = value;
            }
        }
        
        /// <remarks/>
        public string DETAIL {
            get {
                return this.dETAILField;
            }
            set {
                this.dETAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchPattern {
        
        private int userIdField;
        
        private string searchNoField;
        
        private string patternField;
        
        private SearchDbType dbTypeField;
        
        private string strCnpFileField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string SearchNo {
            get {
                return this.searchNoField;
            }
            set {
                this.searchNoField = value;
            }
        }
        
        /// <remarks/>
        public string Pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        public SearchDbType DbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StrCnpFile {
            get {
                return this.strCnpFileField;
            }
            set {
                this.strCnpFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchDbType {
        
        /// <remarks/>
        Cn,
        
        /// <remarks/>
        DocDB,
        
        /// <remarks/>
        Dwpi,
        
        /// <remarks/>
        UserCustomLibrary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultInfo {
        
        private SearchPattern searchPatternField;
        
        private string hitMsgField;
        
        private int hitCountField;
        
        /// <remarks/>
        public SearchPattern SearchPattern {
            get {
                return this.searchPatternField;
            }
            set {
                this.searchPatternField = value;
            }
        }
        
        /// <remarks/>
        public string HitMsg {
            get {
                return this.hitMsgField;
            }
            set {
                this.hitMsgField = value;
            }
        }
        
        /// <remarks/>
        public int HitCount {
            get {
                return this.hitCountField;
            }
            set {
                this.hitCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCnLegalCompletedEventHandler(object sender, GetCnLegalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCnLegalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCnLegalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegalStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegalStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCnLegalDetailCompletedEventHandler(object sender, GetCnLegalDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCnLegalDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCnLegalDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegalStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegalStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCnLegalDetailByAppNoCompletedEventHandler(object sender, GetCnLegalDetailByAppNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCnLegalDetailByAppNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCnLegalDetailByAppNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryFaLvZTCompletedEventHandler(object sender, QueryFaLvZTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFaLvZTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFaLvZTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryFaLvZTGetListCompletedEventHandler(object sender, QueryFaLvZTGetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFaLvZTGetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFaLvZTGetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegalStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegalStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryZhuanYiCompletedEventHandler(object sender, QueryZhuanYiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryZhuanYiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryZhuanYiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegal012[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegal012[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int pagCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryZhiYaCompletedEventHandler(object sender, QueryZhiYaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryZhiYaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryZhiYaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegal015[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegal015[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int pagCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryShiShiXuKeCompletedEventHandler(object sender, QueryShiShiXuKeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryShiShiXuKeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryShiShiXuKeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CnLegal014[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CnLegal014[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int pagCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void QueryFaLvZhuangTaiCompletedEventHandler(object sender, QueryFaLvZhuangTaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFaLvZhuangTaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFaLvZhuangTaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TbCnLegalStatusNew[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TbCnLegalStatusNew[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int pagCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getFaLvZhuangTaiSimpleCompletedEventHandler(object sender, getFaLvZhuangTaiSimpleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFaLvZhuangTaiSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFaLvZhuangTaiSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591